# sap-piper-pipeline - release.yml
parameters:
  - name: skipStage
    type: boolean
    default: false
  - name: overwriteSteps
    type: stepList
    default: []
  - name: preSteps
    type: stepList
    default: []
  - name: postSteps
    type: stepList
    default: []
  - name: checkoutSubmodule
    type: boolean
    default: false
  - name: checkoutLFS
    type: boolean
    default: false
  - name: gitHubComConnectionName  # DEPRECATED. To be removed in the future with v2 of Piper task
    type: string
    default: ""
  - name: gitHubToolsConnectionName
    type: string
    default: ""
  - name: msHostedPool
    type: string
    default: "Azure Pipelines"
  - name: selfHostedPool
    type: string
    default: "Self-hosted"
  - name: poolVmImage
    type: string
    default: "ubuntu-latest"
  - name: disableCachingOnMSHostedAgents
    type: boolean
    default: false
stages:
  - stage: Release
    displayName: Release
    dependsOn: ["Init", "Promote"]
    condition: and(eq(dependencies.Init.outputs['setup.checkIfStepActive.activeRelease'], 'true'), not(or(failed(),canceled())), eq(dependencies.Init.outputs['setup.productiveBranch.onProductiveBranch'], 'true'), eq(dependencies.Promote.result, 'Succeeded'), eq(dependencies.Init.outputs['setup.optimization.isOptimizedAndScheduled'], 'false'), eq('${{ parameters.skipStage }}', 'false'))
    variables:
      sapDefaults_b64: $[ stageDependencies.Init.setup.outputs['piper_defaults.DefaultConfig'] ]
      pipelineEnvironment_b64: $[ stageDependencies.Promote.promote.outputs['piper.PipelineEnv'] ]
      binaryVersion: $[ stageDependencies.Init.setup.outputs['fetch_version.binaryVersion'] ]
      osBinaryVersion: $[ stageDependencies.Init.setup.outputs['fetch_version.osBinaryVersion'] ]
      activeStepsMap: $[ stageDependencies.Init.setup.outputs['checkIfStepActive.activeStepsRelease'] ]
      systemTrustToken: $[ stageDependencies.Init.setup.outputs['getSystemTrustToken.systemTrustSessionToken'] ]
      systemTrustURL: $[ stageDependencies.Init.setup.outputs['getSystemTrustToken.systemTrustURL'] ]

      # the following two variables are only for backward compatibility and should be removed with Piper Azure task v2.
      # they might be used by pipelines with custom stages or in extensions
      # use fetch_version.binaryVersion and fetch_version.osBinaryVersion instead
      piperCacheVersion: $[ stageDependencies.Init.setup.outputs['fetch_version.osBinaryVersion'] ]
      sapPiperCacheVersion: $[ stageDependencies.Init.setup.outputs['fetch_version.binaryVersion'] ]
    pool:
      name: ${{ parameters.msHostedPool }}
      vmImage: ${{ parameters.poolVmImage}}
    jobs:
      - job: release
        steps:
          - checkout: self
            submodules: ${{ parameters.checkoutSubmodule }}
            lfs: ${{ parameters.checkoutLFS }}
          - template: /steps/binary-cache.yml
            parameters:
              disableCaching: ${{ parameters.disableCachingOnMSHostedAgents }}
          - ${{ parameters.preSteps }}
          - ${{ if ne(length(parameters.overwriteSteps), 0) }}:
              - ${{ parameters.overwriteSteps }}
          - ${{ if eq(length(parameters.overwriteSteps), 0) }}:
              - task: piper@1.33.8
                displayName: sapGithubWriteDeployment
                condition: contains(variables.activeStepsMap, '"sapGithubWriteDeployment":true')
                # pipeline should not fail when the step fails.
                continueOnError: true
                inputs:
                  stepName: sapGithubWriteDeployment
                  flags: "--status in_progress --createNew true"
                  restorePipelineDefaults: $(sapDefaults_b64)
                  gitHubConnection: ${{ parameters.gitHubToolsConnectionName }}
              - task: piper@1.33.8
                displayName: terraformExecute
                condition: contains(variables.activeStepsMap, '"terraformExecute":true')
                inputs:
                  stepName: terraformExecute
                  restorePipelineDefaults: $(sapDefaults_b64)
              - task: piper@1.33.8
                displayName: gitopsUpdateDeployment
                condition: contains(variables.activeStepsMap, '"gitopsUpdateDeployment":true')
                inputs:
                  stepName: gitopsUpdateDeployment
                  restorePipelineDefaults: $(sapDefaults_b64)
              - task: piper@1.33.8
                displayName: sapDownloadArtifact
                condition: contains(variables.activeStepsMap, '"sapDownloadArtifact":true')
                inputs:
                  stepName: sapDownloadArtifact
                  flags: "--fromStaging=false"
                  restorePipelineDefaults: $(sapDefaults_b64)
                  gitHubConnection: ${{ parameters.gitHubToolsConnectionName }}
              - task: piper@1.33.8
                displayName: cloudFoundryDeploy
                condition: contains(variables.activeStepsMap, '"cloudFoundryDeploy":true')
                inputs:
                  stepName: cloudFoundryDeploy
                  restorePipelineDefaults: $(sapDefaults_b64)
              - task: piper@1.33.8
                displayName: kubernetesDeploy
                condition: contains(variables.activeStepsMap, '"kubernetesDeploy":true')
                inputs:
                  stepName: kubernetesDeploy
                  restorePipelineDefaults: $(sapDefaults_b64)
              - task: piper@1.33.8
                displayName: sapDwCStageRelease
                condition: contains(variables.activeStepsMap, '"sapDwCStageRelease":true')
                inputs:
                  stepName: sapDwCStageRelease
                  restorePipelineDefaults: $(sapDefaults_b64)
                  gitHubConnection: ${{ parameters.gitHubToolsConnectionName }}
              - task: piper@1.33.8
                displayName: sapCollectInsights
                condition: contains(variables.activeStepsMap, '"sapCollectInsights":true')
                # pipeline should not fail when the dora step fails.
                continueOnError: true
                inputs:
                  stepName: sapCollectInsights
                  restorePipelineDefaults: $(sapDefaults_b64)
                  gitHubConnection: ${{ parameters.gitHubToolsConnectionName }}
              - task: piper@1.33.8
                displayName: githubPublishRelease
                condition: contains(variables.activeStepsMap, '"githubPublishRelease":true')
                inputs:
                  stepName: githubPublishRelease
                  restorePipelineDefaults: $(sapDefaults_b64)
              - script: |
                  if [ "$(Agent.JobStatus)" = "Succeeded" ]; then
                    echo "##vso[task.setvariable variable=deploymentStatusFlag]success"
                  else
                    echo "##vso[task.setvariable variable=deploymentStatusFlag]failure"
                  fi
                displayName: Set deploymentStatusFlag
              - task: piper@1.33.8
                displayName: sapGithubWriteDeployment
                condition: and(always(), contains(variables.activeStepsMap, '"sapGithubWriteDeployment":true'))
                # pipeline should not fail when the step fails.
                continueOnError: true
                inputs:
                  stepName: sapGithubWriteDeployment
                  flags: "--status $(deploymentStatusFlag)"
                  restorePipelineDefaults: $(sapDefaults_b64)
                  gitHubConnection: ${{ parameters.gitHubToolsConnectionName }}
          - ${{ parameters.postSteps }}
