// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GCSClient is an autogenerated mock type for the GCSClient type
type GCSClient struct {
	mock.Mock
}

type GCSClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GCSClient) EXPECT() *GCSClient_Expecter {
	return &GCSClient_Expecter{mock: &_m.Mock}
}

// DownloadFile provides a mock function with given fields: ctx, bucketID, sourcePath, targetPath
func (_m *GCSClient) DownloadFile(ctx context.Context, bucketID string, sourcePath string, targetPath string) error {
	ret := _m.Called(ctx, bucketID, sourcePath, targetPath)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, bucketID, sourcePath, targetPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GCSClient_DownloadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFile'
type GCSClient_DownloadFile_Call struct {
	*mock.Call
}

// DownloadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketID string
//   - sourcePath string
//   - targetPath string
func (_e *GCSClient_Expecter) DownloadFile(ctx interface{}, bucketID interface{}, sourcePath interface{}, targetPath interface{}) *GCSClient_DownloadFile_Call {
	return &GCSClient_DownloadFile_Call{Call: _e.mock.On("DownloadFile", ctx, bucketID, sourcePath, targetPath)}
}

func (_c *GCSClient_DownloadFile_Call) Run(run func(ctx context.Context, bucketID string, sourcePath string, targetPath string)) *GCSClient_DownloadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *GCSClient_DownloadFile_Call) Return(_a0 error) *GCSClient_DownloadFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GCSClient_DownloadFile_Call) RunAndReturn(run func(context.Context, string, string, string) error) *GCSClient_DownloadFile_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function with given fields: ctx, bucketID
func (_m *GCSClient) ListFiles(ctx context.Context, bucketID string) ([]string, error) {
	ret := _m.Called(ctx, bucketID)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, bucketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, bucketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bucketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GCSClient_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type GCSClient_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketID string
func (_e *GCSClient_Expecter) ListFiles(ctx interface{}, bucketID interface{}) *GCSClient_ListFiles_Call {
	return &GCSClient_ListFiles_Call{Call: _e.mock.On("ListFiles", ctx, bucketID)}
}

func (_c *GCSClient_ListFiles_Call) Run(run func(ctx context.Context, bucketID string)) *GCSClient_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GCSClient_ListFiles_Call) Return(_a0 []string, _a1 error) *GCSClient_ListFiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GCSClient_ListFiles_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *GCSClient_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function with given fields: ctx, bucketID, sourcePath, targetPath
func (_m *GCSClient) UploadFile(ctx context.Context, bucketID string, sourcePath string, targetPath string) error {
	ret := _m.Called(ctx, bucketID, sourcePath, targetPath)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, bucketID, sourcePath, targetPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GCSClient_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type GCSClient_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketID string
//   - sourcePath string
//   - targetPath string
func (_e *GCSClient_Expecter) UploadFile(ctx interface{}, bucketID interface{}, sourcePath interface{}, targetPath interface{}) *GCSClient_UploadFile_Call {
	return &GCSClient_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, bucketID, sourcePath, targetPath)}
}

func (_c *GCSClient_UploadFile_Call) Run(run func(ctx context.Context, bucketID string, sourcePath string, targetPath string)) *GCSClient_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *GCSClient_UploadFile_Call) Return(_a0 error) *GCSClient_UploadFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GCSClient_UploadFile_Call) RunAndReturn(run func(context.Context, string, string, string) error) *GCSClient_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewGCSClient creates a new instance of GCSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGCSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GCSClient {
	mock := &GCSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UploadFile provides a mock function with given fields: ctx, bucketID, sourcePath, targetPath
func (_m *GCSClient) Close() error {
	return nil
}
