//go:build unit
// +build unit

// Code generated by mockery v2.53.3. DO NOT EDIT.

package dwc

import mock "github.com/stretchr/testify/mock"

// mockCliReleaseResolver is an autogenerated mock type for the cliReleaseResolver type
type mockCliReleaseResolver struct {
	mock.Mock
}

// GetCLIReleaseURL provides a mock function with given fields: withToken
func (_m *mockCliReleaseResolver) GetCLIReleaseURL(withToken string) (string, error) {
	ret := _m.Called(withToken)

	if len(ret) == 0 {
		panic("no return value specified for GetCLIReleaseURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(withToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(withToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(withToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockCliReleaseResolver creates a new instance of mockCliReleaseResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCliReleaseResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCliReleaseResolver {
	mock := &mockCliReleaseResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
