//go:build unit
// +build unit

// Code generated by mockery v2.14.0. DO NOT EDIT.

package dwc

import mock "github.com/stretchr/testify/mock"

// mockFilePatternMover is an autogenerated mock type for the filePatternMover type
type mockFilePatternMover struct {
	mock.Mock
}

// move provides a mock function with given fields: objectsToMove, targetFolder, executorFactory
func (_m *mockFilePatternMover) move(objectsToMove []string, targetFolder string, executorFactory BlockingExecutorFactory) error {
	ret := _m.Called(objectsToMove, targetFolder, executorFactory)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, string, BlockingExecutorFactory) error); ok {
		r0 = rf(objectsToMove, targetFolder, executorFactory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMockFilePatternMover interface {
	mock.TestingT
	Cleanup(func())
}

// newMockFilePatternMover creates a new instance of mockFilePatternMover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockFilePatternMover(t mockConstructorTestingTnewMockFilePatternMover) *mockFilePatternMover {
	mock := &mockFilePatternMover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
