//go:build unit
// +build unit

// Code generated by mockery v2.14.0. DO NOT EDIT.

package dwc

import mock "github.com/stretchr/testify/mock"

// mockGlobMatcher is an autogenerated mock type for the globMatcher type
type mockGlobMatcher struct {
	mock.Mock
}

// Glob provides a mock function with given fields: pattern
func (_m *mockGlobMatcher) Glob(pattern string) ([]string, error) {
	ret := _m.Called(pattern)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockGlobMatcher interface {
	mock.TestingT
	Cleanup(func())
}

// newMockGlobMatcher creates a new instance of mockGlobMatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockGlobMatcher(t mockConstructorTestingTnewMockGlobMatcher) *mockGlobMatcher {
	mock := &mockGlobMatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
