//go:build unit
// +build unit

// Code generated by mockery v2.14.0. DO NOT EDIT.

package dwc

import (
	mock "github.com/stretchr/testify/mock"
	chartutil "helm.sh/helm/v3/pkg/chartutil"
)

// helmChartMockUtils is an autogenerated mock type for the helmChartUtils type
type helmChartMockUtils struct {
	mock.Mock
}

// IsChartDir provides a mock function with given fields: dirName
func (_m *helmChartMockUtils) IsChartDir(dirName string) (bool, error) {
	ret := _m.Called(dirName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(dirName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dirName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadValuesFile provides a mock function with given fields: filename
func (_m *helmChartMockUtils) ReadValuesFile(filename string) (chartutil.Values, error) {
	ret := _m.Called(filename)

	var r0 chartutil.Values
	if rf, ok := ret.Get(0).(func(string) chartutil.Values); ok {
		r0 = rf(filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chartutil.Values)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewHelmChartMockUtils interface {
	mock.TestingT
	Cleanup(func())
}

// newHelmChartMockUtils creates a new instance of helmChartMockUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newHelmChartMockUtils(t mockConstructorTestingTnewHelmChartMockUtils) *helmChartMockUtils {
	mock := &helmChartMockUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
