//go:build unit
// +build unit

// Code generated by mockery v2.14.0. DO NOT EDIT.

package dwc

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// blockingExecutorFactoryMock is an autogenerated mock type for the BlockingExecutorFactory type
type blockingExecutorFactoryMock struct {
	mock.Mock
}

// CreateExecutor provides a mock function with given fields: stdout, stderr
func (_m *blockingExecutorFactoryMock) CreateExecutor(stdout io.Writer, stderr io.Writer) BlockingExecutor {
	ret := _m.Called(stdout, stderr)

	var r0 BlockingExecutor
	if rf, ok := ret.Get(0).(func(io.Writer, io.Writer) BlockingExecutor); ok {
		r0 = rf(stdout, stderr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(BlockingExecutor)
		}
	}

	return r0
}

type mockConstructorTestingTnewBlockingExecutorFactoryMock interface {
	mock.TestingT
	Cleanup(func())
}

// newBlockingExecutorFactoryMock creates a new instance of blockingExecutorFactoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newBlockingExecutorFactoryMock(t mockConstructorTestingTnewBlockingExecutorFactoryMock) *blockingExecutorFactoryMock {
	mock := &blockingExecutorFactoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
