//go:build unit
// +build unit

// Code generated by mockery v2.14.0. DO NOT EDIT.

package dwc

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockZipWriter is an autogenerated mock type for the zipWriter type
type mockZipWriter struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *mockZipWriter) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: name
func (_m *mockZipWriter) Create(name string) (io.Writer, error) {
	ret := _m.Called(name)

	var r0 io.Writer
	if rf, ok := ret.Get(0).(func(string) io.Writer); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockZipWriter interface {
	mock.TestingT
	Cleanup(func())
}

// newMockZipWriter creates a new instance of mockZipWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockZipWriter(t mockConstructorTestingTnewMockZipWriter) *mockZipWriter {
	mock := &mockZipWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
