// Code generated by mockery v2.53.3. DO NOT EDIT.

package dwc

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// descriptorFileMockUtils is an autogenerated mock type for the descriptorFileUtils type
type descriptorFileMockUtils struct {
	mock.Mock
}

// FileRead provides a mock function with given fields: path
func (_m *descriptorFileMockUtils) FileRead(path string) ([]byte, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for FileRead")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileRemove provides a mock function with given fields: path
func (_m *descriptorFileMockUtils) FileRemove(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for FileRemove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileWrite provides a mock function with given fields: name, data, perm
func (_m *descriptorFileMockUtils) FileWrite(name string, data []byte, perm fs.FileMode) error {
	ret := _m.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for FileWrite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, fs.FileMode) error); ok {
		r0 = rf(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MkdirAll provides a mock function with given fields: path, perm
func (_m *descriptorFileMockUtils) MkdirAll(path string, perm fs.FileMode) error {
	ret := _m.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, fs.FileMode) error); ok {
		r0 = rf(path, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newDescriptorFileMockUtils creates a new instance of descriptorFileMockUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newDescriptorFileMockUtils(t interface {
	mock.TestingT
	Cleanup(func())
}) *descriptorFileMockUtils {
	mock := &descriptorFileMockUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
