//go:build unit
// +build unit

// Code generated by mockery v2.14.0. DO NOT EDIT.

package dwc

import mock "github.com/stretchr/testify/mock"

// mockArtifactCompressor is an autogenerated mock type for the ArtifactCompressor type
type mockArtifactCompressor struct {
	mock.Mock
}

// compressArtifact provides a mock function with given fields: descriptor, artifactSourceDir
func (_m *mockArtifactCompressor) compressArtifact(descriptor ArtifactDescriptor, artifactSourceDir string) error {
	ret := _m.Called(descriptor, artifactSourceDir)

	var r0 error
	if rf, ok := ret.Get(0).(func(ArtifactDescriptor, string) error); ok {
		r0 = rf(descriptor, artifactSourceDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMockArtifactCompressor interface {
	mock.TestingT
	Cleanup(func())
}

// newMockArtifactCompressor creates a new instance of mockArtifactCompressor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockArtifactCompressor(t mockConstructorTestingTnewMockArtifactCompressor) *mockArtifactCompressor {
	mock := &mockArtifactCompressor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
