//go:build unit
// +build unit

// Code generated by mockery v2.14.0. DO NOT EDIT.

package dwc

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockStageWatchOrchestrator is an autogenerated mock type for the StageWatchOrchestrator type
type mockStageWatchOrchestrator struct {
	mock.Mock
}

// WatchVectorDeployments provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *mockStageWatchOrchestrator) WatchVectorDeployments(_a0 []PromotionResultEntry, _a1 io.Writer, _a2 CLICommandExecutor, _a3 BlockingExecutorFactory, _a4 ArtifactDescriptor) error {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	var r0 error
	if rf, ok := ret.Get(0).(func([]PromotionResultEntry, io.Writer, CLICommandExecutor, BlockingExecutorFactory, ArtifactDescriptor) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMockStageWatchOrchestrator interface {
	mock.TestingT
	Cleanup(func())
}

// newMockStageWatchOrchestrator creates a new instance of mockStageWatchOrchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockStageWatchOrchestrator(t mockConstructorTestingTnewMockStageWatchOrchestrator) *mockStageWatchOrchestrator {
	mock := &mockStageWatchOrchestrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
