//go:build unit
// +build unit

// Code generated by mockery v2.14.0. DO NOT EDIT.

package dwc

import mock "github.com/stretchr/testify/mock"

// yamlMockUtils is an autogenerated mock type for the yamlUtils type
type yamlMockUtils struct {
	mock.Mock
}

// Marshal provides a mock function with given fields: in
func (_m *yamlMockUtils) Marshal(in interface{}) ([]byte, error) {
	ret := _m.Called(in)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(interface{}) []byte); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unmarshal provides a mock function with given fields: in, out
func (_m *yamlMockUtils) Unmarshal(in []byte, out interface{}) error {
	ret := _m.Called(in, out)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, interface{}) error); ok {
		r0 = rf(in, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewYamlMockUtils interface {
	mock.TestingT
	Cleanup(func())
}

// newYamlMockUtils creates a new instance of yamlMockUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newYamlMockUtils(t mockConstructorTestingTnewYamlMockUtils) *yamlMockUtils {
	mock := &yamlMockUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
