//go:build unit
// +build unit

// Code generated by mockery v2.14.0. DO NOT EDIT.

package dwc

import mock "github.com/stretchr/testify/mock"

// mockMetadataCollector is an autogenerated mock type for the MetadataCollector type
type mockMetadataCollector struct {
	mock.Mock
}

// GetMetadataEntry provides a mock function with given fields: element
func (_m *mockMetadataCollector) GetMetadataEntry(element string) (string, error) {
	ret := _m.Called(element)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(element)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(element)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockMetadataCollector interface {
	mock.TestingT
	Cleanup(func())
}

// newMockMetadataCollector creates a new instance of mockMetadataCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockMetadataCollector(t mockConstructorTestingTnewMockMetadataCollector) *mockMetadataCollector {
	mock := &mockMetadataCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
