//go:build unit
// +build unit

// Code generated by mockery v2.14.0. DO NOT EDIT.

package dwc

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// mockDirReader is an autogenerated mock type for the dirReader type
type mockDirReader struct {
	mock.Mock
}

// ReadDir provides a mock function with given fields: dirname
func (_m *mockDirReader) ReadDir(dirname string) ([]fs.DirEntry, error) {
	ret := _m.Called(dirname)

	var r0 []fs.DirEntry
	if rf, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = rf(dirname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dirname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockDirReader interface {
	mock.TestingT
	Cleanup(func())
}

// newMockDirReader creates a new instance of mockDirReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockDirReader(t mockConstructorTestingTnewMockDirReader) *mockDirReader {
	mock := &mockDirReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
