//go:build unit
// +build unit

// Code generated by mockery v2.14.0. DO NOT EDIT.

package dwc

import mock "github.com/stretchr/testify/mock"

// mockLoginDescriptor is an autogenerated mock type for the LoginDescriptor type
type mockLoginDescriptor struct {
	mock.Mock
}

// buildLoginCommand provides a mock function with given fields:
func (_m *mockLoginDescriptor) buildLoginCommand() (dwcCommand, error) {
	ret := _m.Called()

	var r0 dwcCommand
	if rf, ok := ret.Get(0).(func() dwcCommand); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dwcCommand)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockLoginDescriptor interface {
	mock.TestingT
	Cleanup(func())
}

// newMockLoginDescriptor creates a new instance of mockLoginDescriptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockLoginDescriptor(t mockConstructorTestingTnewMockLoginDescriptor) *mockLoginDescriptor {
	mock := &mockLoginDescriptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
