// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"reflect"
	"strings"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/gcs"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/bmatcuk/doublestar"
	"github.com/spf13/cobra"
)

type sapCreateFosstarsReportOptions struct {
	BuildDescriptor             string   `json:"buildDescriptor,omitempty"`
	SCMURL                      string   `json:"sCMUrl,omitempty"`
	Branch                      string   `json:"branch,omitempty"`
	FosstarsQueryServiceBaseURL string   `json:"fosstarsQueryServiceBaseUrl,omitempty"`
	FosstarsClientSuffix        string   `json:"fosstarsClientSuffix,omitempty"`
	RatingNameSpace             string   `json:"ratingNameSpace,omitempty"`
	RatingName                  string   `json:"ratingName,omitempty"`
	RatingLabelThreshold        string   `json:"ratingLabelThreshold,omitempty" validate:"possible-values=BAD MODERATE NONE"`
	RatingValueThreshold        int      `json:"ratingValueThreshold,omitempty"`
	FailOnUnclearRatings        bool     `json:"failOnUnclearRatings,omitempty"`
	BuildAllMavenPomFiles       bool     `json:"buildAllMavenPomFiles,omitempty"`
	ExcludedLibraries           []string `json:"excludedLibraries,omitempty"`
	IncludeTransitiveDependency bool     `json:"includeTransitiveDependency,omitempty"`
	ExcludeSAPInternalLibraries bool     `json:"excludeSAPInternalLibraries,omitempty"`
	ExcludeTestDevDependencies  bool     `json:"excludeTestDevDependencies,omitempty"`
	RequestedRetryCount         int      `json:"requestedRetryCount,omitempty"`
	SkipSCMCheckOut             bool     `json:"skipSCMCheckOut,omitempty"`
	Username                    string   `json:"username,omitempty"`
	Password                    string   `json:"password,omitempty"`
	CustomTLSCertificateLinks   []string `json:"customTlsCertificateLinks,omitempty"`
	GlobalSettingsFile          string   `json:"globalSettingsFile,omitempty"`
	BuildQuality                string   `json:"buildQuality,omitempty"`
}

type sapCreateFosstarsReportReports struct {
}

func (p *sapCreateFosstarsReportReports) persist(stepConfig sapCreateFosstarsReportOptions, gcpJsonKeyFilePath string, gcsBucketId string, gcsFolderPath string, gcsSubFolder string) {
	if gcsBucketId == "" {
		log.Entry().Info("persisting reports to GCS is disabled, because gcsBucketId is empty")
		return
	}
	log.Entry().Info("Uploading reports to Google Cloud Storage...")
	content := []gcs.ReportOutputParam{
		{FilePattern: "fosstars-report/*.json", ParamRef: "", StepResultType: "fosstars"},
		{FilePattern: "fosstars-report/*.html", ParamRef: "", StepResultType: "fosstars"},
	}

	gcsClient, err := gcs.NewClient(gcpJsonKeyFilePath, "")
	if err != nil {
		log.Entry().Errorf("creation of GCS client failed: %v", err)
		return
	}
	defer gcsClient.Close()
	structVal := reflect.ValueOf(&stepConfig).Elem()
	inputParameters := map[string]string{}
	for i := 0; i < structVal.NumField(); i++ {
		field := structVal.Type().Field(i)
		if field.Type.String() == "string" {
			paramName := strings.Split(field.Tag.Get("json"), ",")
			paramValue, _ := structVal.Field(i).Interface().(string)
			inputParameters[paramName[0]] = paramValue
		}
	}
	if err := gcs.PersistReportsToGCS(gcsClient, content, inputParameters, gcsFolderPath, gcsBucketId, gcsSubFolder, doublestar.Glob, os.Stat); err != nil {
		log.Entry().Errorf("failed to persist reports: %v", err)
	}
}

// SapCreateFosstarsReportCommand Create Fosstars OSS rating report
func SapCreateFosstarsReportCommand() *cobra.Command {
	const STEP_NAME = "sapCreateFosstarsReport"

	metadata := sapCreateFosstarsReportMetadata()
	var stepConfig sapCreateFosstarsReportOptions
	var startTime time.Time
	var reports sapCreateFosstarsReportReports
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapCreateFosstarsReportCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "Create Fosstars OSS rating report",
		Long: `Create Fosstars OSS rating report based on open source dependencies used in the project.
It is currently in **BETA** mode, thus incompatible changes may occur although we aim to limit those kind of changes.

You find details about Fosstars on the [Fosstars GitHub](https://go.sap.corp/phosphor_fosstars)`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.Username)
			log.RegisterSecret(stepConfig.Password)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				reports.persist(stepConfig, piperOsCmd.GeneralConfig.GCPJsonKeyFilePath, piperOsCmd.GeneralConfig.GCSBucketId, piperOsCmd.GeneralConfig.GCSFolderPath, piperOsCmd.GeneralConfig.GCSSubFolder)
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapCreateFosstarsReport(stepConfig, &stepTelemetryData)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapCreateFosstarsReportFlags(createSapCreateFosstarsReportCmd, &stepConfig)
	return createSapCreateFosstarsReportCmd
}

func addSapCreateFosstarsReportFlags(cmd *cobra.Command, stepConfig *sapCreateFosstarsReportOptions) {
	cmd.Flags().StringVar(&stepConfig.BuildDescriptor, "buildDescriptor", os.Getenv("PIPER_buildDescriptor"), "Direct path to build Descriptor file (like Maven `pom.xml` or `package.json` etc. ).")
	cmd.Flags().StringVar(&stepConfig.SCMURL, "sCMUrl", os.Getenv("PIPER_sCMUrl"), "The source code management url.")
	cmd.Flags().StringVar(&stepConfig.Branch, "branch", os.Getenv("PIPER_branch"), "The source code managent branch.")
	cmd.Flags().StringVar(&stepConfig.FosstarsQueryServiceBaseURL, "fosstarsQueryServiceBaseUrl", `https://fosstars.tools.sap.corp`, "The url to the fosstars service.")
	cmd.Flags().StringVar(&stepConfig.FosstarsClientSuffix, "fosstarsClientSuffix", os.Getenv("PIPER_fosstarsClientSuffix"), "The client suffix for fosstars service.")
	cmd.Flags().StringVar(&stepConfig.RatingNameSpace, "ratingNameSpace", `Phosphor`, "The Namespace of the rating you are requesting for.")
	cmd.Flags().StringVar(&stepConfig.RatingName, "ratingName", `Security`, "The kind of rating you are requesting for.")
	cmd.Flags().StringVar(&stepConfig.RatingLabelThreshold, "ratingLabelThreshold", `NONE`, "The threshold value of the rating Label for the build to fail.")
	cmd.Flags().IntVar(&stepConfig.RatingValueThreshold, "ratingValueThreshold", 0, "The threshold value of the rating Value between 1-10 for the build to fail.")
	cmd.Flags().BoolVar(&stepConfig.FailOnUnclearRatings, "failOnUnclearRatings", false, "Fail the build on occurrence of at least one UNCLEAR rating")
	cmd.Flags().BoolVar(&stepConfig.BuildAllMavenPomFiles, "buildAllMavenPomFiles", false, "Build maven project by getting all pom files in the project recursively.")
	cmd.Flags().StringSliceVar(&stepConfig.ExcludedLibraries, "excludedLibraries", []string{}, "The list of librarires which should be excluded from the build failure due to bad ratings.")
	cmd.Flags().BoolVar(&stepConfig.IncludeTransitiveDependency, "includeTransitiveDependency", true, "Include the transitive dependencies in the Fosstars report.")
	cmd.Flags().BoolVar(&stepConfig.ExcludeSAPInternalLibraries, "excludeSAPInternalLibraries", false, "Option to exclude SAP internal libraries/dependencies from Fosstars report.")
	cmd.Flags().BoolVar(&stepConfig.ExcludeTestDevDependencies, "excludeTestDevDependencies", true, "Option to exclude test/dev dependencies from Fosstars report.")
	cmd.Flags().IntVar(&stepConfig.RequestedRetryCount, "requestedRetryCount", 10, "The number of times the ratings should be requested until all the ratings are in CALCULATED state.")
	cmd.Flags().BoolVar(&stepConfig.SkipSCMCheckOut, "skipSCMCheckOut", false, "Skip the checkout of SCM and check for the build descriptors in the current folder.")
	cmd.Flags().StringVar(&stepConfig.Username, "username", os.Getenv("PIPER_username"), "User name for git authentication")
	cmd.Flags().StringVar(&stepConfig.Password, "password", os.Getenv("PIPER_password"), "Password/token for git authentication.")
	cmd.Flags().StringSliceVar(&stepConfig.CustomTLSCertificateLinks, "customTlsCertificateLinks", []string{}, "List of download links to custom TLS certificates. This is required to ensure trusted connections to instances with repositories (like nexus) when publish flag is set to true.")
	cmd.Flags().StringVar(&stepConfig.GlobalSettingsFile, "globalSettingsFile", `https://int.repositories.cloud.sap/artifactory/build-releases/settings.xml`, "Maven only - Path to the mvn settings file that should be used as global settings file.")
	cmd.Flags().StringVar(&stepConfig.BuildQuality, "buildQuality", os.Getenv("PIPER_buildQuality"), "Defines the build quality for the build job.")

	cmd.MarkFlagRequired("username")
	cmd.MarkFlagRequired("password")
}

// retrieve step metadata
func sapCreateFosstarsReportMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapCreateFosstarsReport",
			Aliases:     []config.Alias{},
			Description: "Create Fosstars OSS rating report",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "gitHttpsCredentialsId", Description: "Jenkins 'Username with password' credentials ID containing username/password for http access to your git repository.", Type: "jenkins"},
				},
				Parameters: []config.StepParameters{
					{
						Name:        "buildDescriptor",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_buildDescriptor"),
					},
					{
						Name:        "sCMUrl",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_sCMUrl"),
					},
					{
						Name:        "branch",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_branch"),
					},
					{
						Name:        "fosstarsQueryServiceBaseUrl",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `https://fosstars.tools.sap.corp`,
					},
					{
						Name:        "fosstarsClientSuffix",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_fosstarsClientSuffix"),
					},
					{
						Name:        "ratingNameSpace",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `Phosphor`,
					},
					{
						Name:        "ratingName",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `Security`,
					},
					{
						Name:        "ratingLabelThreshold",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `NONE`,
					},
					{
						Name:        "ratingValueThreshold",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "int",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     0,
					},
					{
						Name:        "failOnUnclearRatings",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "buildAllMavenPomFiles",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "excludedLibraries",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     []string{},
					},
					{
						Name:        "includeTransitiveDependency",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     true,
					},
					{
						Name:        "excludeSAPInternalLibraries",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "excludeTestDevDependencies",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     true,
					},
					{
						Name:        "requestedRetryCount",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "int",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     10,
					},
					{
						Name:        "skipSCMCheckOut",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name: "username",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "gitHttpsCredentialsId",
								Param: "username",
								Type:  "secret",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_username"),
					},
					{
						Name: "password",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "gitHttpsCredentialsId",
								Param: "password",
								Type:  "secret",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_password"),
					},
					{
						Name:        "customTlsCertificateLinks",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     []string{},
					},
					{
						Name:        "globalSettingsFile",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "STEPS", "STAGES", "PARAMETERS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "maven/globalSettingsFile"}},
						Default:     `https://int.repositories.cloud.sap/artifactory/build-releases/settings.xml`,
					},
					{
						Name:        "buildQuality",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "STEPS", "STAGES", "PARAMETERS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "xMakeBuildQuality"}},
						Default:     os.Getenv("PIPER_buildQuality"),
					},
				},
			},
			Containers: []config.Container{
				{Image: "maven:3.6-jdk-8"},
			},
			Outputs: config.StepOutputs{
				Resources: []config.StepResources{
					{
						Name: "reports",
						Type: "reports",
						Parameters: []map[string]interface{}{
							{"filePattern": "fosstars-report/*.json", "type": "fosstars"},
							{"filePattern": "fosstars-report/*.html", "type": "fosstars"},
						},
					},
				},
			},
		},
	}
	return theMetaData
}
