// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/spf13/cobra"
)

type sapCheckECCNComplianceOptions struct {
	ServerURL   string `json:"serverUrl,omitempty"`
	PpmsID      string `json:"ppmsID,omitempty"`
	EccnDetails bool   `json:"eccnDetails,omitempty"`
	Password    string `json:"password,omitempty"`
	Username    string `json:"username,omitempty"`
}

// SapCheckECCNComplianceCommand Checks if the PPMS object already has an Export Control Classification.
func SapCheckECCNComplianceCommand() *cobra.Command {
	const STEP_NAME = "sapCheckECCNCompliance"

	metadata := sapCheckECCNComplianceMetadata()
	var stepConfig sapCheckECCNComplianceOptions
	var startTime time.Time
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapCheckECCNComplianceCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "Checks if the PPMS object already has an Export Control Classification.",
		Long: `Checks related to [ECCN Manager](https://wiki.one.int.sap/wiki/display/DevFw/ECCN+Manager) can be integrated in your Piper pipeline. If you configure the sapCheckECCNCompliance step properly, your pipeline will check whether the PPMS Object is ECCN classified and gives the following  messages:
1. Success message in case the questionnaire is both EU and US classified.
For example: ` + "`" + `"Questionnaire for CV/PV - <ppms_object_name> is classified with EU classification <classification_value> and US classification <classification_value>!"` + "`" + `
2.  Error message in case the questionnaire is only EU classified.
For example: ` + "`" + `"Questionnaire for CV/PV - <ppms_object_name> is partially classified with EU classification <classification_value> and no US classification"` + "`" + `
3.  Error message in case classification is not found.
For example: ` + "`" + `"Questionnaire for CV/PV - <ppms_object_name> is not yet classified"` + "`" + `
4.  Warning message in case of version is greater than one, and the earlier version is both EU and US classification.
For example: ` + "`" + `"Questionnaire for CV/PV - <ppms_object_name> in reclassification with previous EU classification <classification_value> and US classification <classification_value>!"` + "`" + `
5. Information message if questionnaire is not yet created.
For example: '"No ECCN data exist for supplied PPMS Object Number"'
6. Information message if currently there's a problem in fetching data of the PPMS Object number from PPMS system due to communication failures.
For example: '"Issue while fetching details from PPMS"'

It is currently in BETA mode; thus, incompatible changes may occur although we aim to limit those kinds of changes.
> The ECCN Manager Tool is used as part of the [ECCN data collection process](https://sap.sharepoint.com/sites/126097/SitePages/Export-Control-Classification---Process.aspx).The tool allows you to store export control relevant data for the PPMS entities Software Component Version and Product Version.
> The data is stored in questionnaires consisting of a set of questions.

!!! note "Support channel"
    Create an [IT Direct](https://itdirect.wdf.sap.corp/sap(bD1lbiZjPTAwMSZkPW1pbg==)/bc/bsp/sap/crm_ui_start/default.htm?crm-object-type=AIC_OB_INCIDENT&crm-object-action=D&PROCESS_TYPE=ZINE&CAT_ID=IMFIT_TOOLS_ECCN) ticket (Category ID: **IMFIT_TOOLS_ECCN**) to reach ECCN Manager team for an issue or a feature request.`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.Password)
			log.RegisterSecret(stepConfig.Username)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapCheckECCNCompliance(stepConfig, &stepTelemetryData)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapCheckECCNComplianceFlags(createSapCheckECCNComplianceCmd, &stepConfig)
	return createSapCheckECCNComplianceCmd
}

func addSapCheckECCNComplianceFlags(cmd *cobra.Command, stepConfig *sapCheckECCNComplianceOptions) {
	cmd.Flags().StringVar(&stepConfig.ServerURL, "serverUrl", `https://ifp.bss.net.sap`, "HTTPS server URL for ifp system")
	cmd.Flags().StringVar(&stepConfig.PpmsID, "ppmsID", os.Getenv("PIPER_ppmsID"), "PPMS object number of PPMS software component version or PPMS product version.")
	cmd.Flags().BoolVar(&stepConfig.EccnDetails, "eccnDetails", false, "When true, will provide details on the comprised components.")
	cmd.Flags().StringVar(&stepConfig.Password, "password", os.Getenv("PIPER_password"), "Password for IFP system.")
	cmd.Flags().StringVar(&stepConfig.Username, "username", os.Getenv("PIPER_username"), "User name for IFP system.")

	cmd.MarkFlagRequired("serverUrl")
	cmd.MarkFlagRequired("ppmsID")
	cmd.MarkFlagRequired("password")
	cmd.MarkFlagRequired("username")
}

// retrieve step metadata
func sapCheckECCNComplianceMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapCheckECCNCompliance",
			Aliases:     []config.Alias{},
			Description: "Checks if the PPMS object already has an Export Control Classification.",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "eccnCredentialsId", Description: "Jenkins 'File' credentials ID containing the key file to authenticate to IFP system.", Type: "jenkins"},
				},
				Parameters: []config.StepParameters{
					{
						Name:        "serverUrl",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{},
						Default:     `https://ifp.bss.net.sap`,
					},
					{
						Name:        "ppmsID",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_ppmsID"),
					},
					{
						Name:        "eccnDetails",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name: "password",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "eccnCredentialsId",
								Param: "password",
								Type:  "secret",
							},

							{
								Name:    "eccnCredentialsVaultSecretName",
								Type:    "vaultSecret",
								Default: "eccn",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_password"),
					},
					{
						Name: "username",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "eccnCredentialsId",
								Param: "username",
								Type:  "secret",
							},

							{
								Name:    "eccnCredentialsVaultSecretName",
								Type:    "vaultSecret",
								Default: "eccn",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_username"),
					},
				},
			},
		},
	}
	return theMetaData
}
