// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/spf13/cobra"
)

type sapCumulusDownloadOptions struct {
	FilePattern           string `json:"filePattern,omitempty"`
	JSONKeyFilePath       string `json:"jsonKeyFilePath,omitempty"`
	Token                 string `json:"token,omitempty"`
	PipelineID            string `json:"pipelineId,omitempty"`
	StepResultType        string `json:"stepResultType,omitempty"`
	SubFolderPath         string `json:"subFolderPath,omitempty"`
	TargetPath            string `json:"targetPath,omitempty"`
	Version               string `json:"version,omitempty"`
	GitHeadCommitID       string `json:"gitHeadCommitId,omitempty"`
	UseCommitIDForCumulus bool   `json:"useCommitIdForCumulus,omitempty"`
}

// SapCumulusDownloadCommand Download files from Cumulus
func SapCumulusDownloadCommand() *cobra.Command {
	const STEP_NAME = "sapCumulusDownload"

	metadata := sapCumulusDownloadMetadata()
	var stepConfig sapCumulusDownloadOptions
	var startTime time.Time
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapCumulusDownloadCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "Download files from Cumulus",
		Long: `This step allows to download files from Cumulus.

You find details about Cumulus in the [Cumulus Wiki](https://wiki.wdf.sap.corp/wiki/x/nCu1g).

More information about the Cumulus integration in the general purpose pipeline template can be found [here](https://go.sap.corp/piper/stages/cumulus-integration/).`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.JSONKeyFilePath)
			log.RegisterSecret(stepConfig.Token)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapCumulusDownload(stepConfig, &stepTelemetryData)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapCumulusDownloadFlags(createSapCumulusDownloadCmd, &stepConfig)
	return createSapCumulusDownloadCmd
}

func addSapCumulusDownloadFlags(cmd *cobra.Command, stepConfig *sapCumulusDownloadOptions) {
	cmd.Flags().StringVar(&stepConfig.FilePattern, "filePattern", os.Getenv("PIPER_filePattern"), "Pattern of the files to be downloaded using doublestar wildcard logic (e.g. **/*.xml).")
	cmd.Flags().StringVar(&stepConfig.JSONKeyFilePath, "jsonKeyFilePath", os.Getenv("PIPER_jsonKeyFilePath"), "File path to Google Cloud JSON key file.")
	cmd.Flags().StringVar(&stepConfig.Token, "token", os.Getenv("PIPER_token"), "The token used to authenticate with the Google Cloud Storage service. It is provided by System Trust, so usually there is no need to set this parameter.")
	cmd.Flags().StringVar(&stepConfig.PipelineID, "pipelineId", os.Getenv("PIPER_pipelineId"), "Id of the Cumulus pipeline.")
	cmd.Flags().StringVar(&stepConfig.StepResultType, "stepResultType", `general`, "Step result type to be used in Cumulus store.")
	cmd.Flags().StringVar(&stepConfig.SubFolderPath, "subFolderPath", os.Getenv("PIPER_subFolderPath"), "Used to logically separate results of the same type.")
	cmd.Flags().StringVar(&stepConfig.TargetPath, "targetPath", os.Getenv("PIPER_targetPath"), "Path on disk where we want to save the downloaded files.")
	cmd.Flags().StringVar(&stepConfig.Version, "version", os.Getenv("PIPER_version"), "The version assigned to the uploaded documents.")
	cmd.Flags().StringVar(&stepConfig.GitHeadCommitID, "gitHeadCommitId", os.Getenv("PIPER_gitHeadCommitId"), "Specifies the headcommitId to be sent as part of the environment information.")
	cmd.Flags().BoolVar(&stepConfig.UseCommitIDForCumulus, "useCommitIdForCumulus", false, "Parameter in Beta mode. To be set to true if cumulus storage needs to be only with commit id.")

	cmd.MarkFlagRequired("filePattern")
	cmd.MarkFlagRequired("jsonKeyFilePath")
	cmd.MarkFlagRequired("pipelineId")
	cmd.MarkFlagRequired("version")
}

// retrieve step metadata
func sapCumulusDownloadMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapCumulusDownload",
			Aliases:     []config.Alias{},
			Description: "Download files from Cumulus",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "cumulusFileCredentialsId", Description: "Jenkins 'File' credentials ID containing the key file to authenticate to Cumulus on the Google Cloud Platform.", Type: "jenkins"},
				},
				Parameters: []config.StepParameters{
					{
						Name:        "filePattern",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_filePattern"),
					},
					{
						Name: "jsonKeyFilePath",
						ResourceRef: []config.ResourceReference{
							{
								Name: "cumulusFileCredentialsId",
								Type: "secret",
							},

							{
								Name:    "cumulusFileCredentialsVaultSecretName",
								Type:    "vaultSecretFile",
								Default: "cumulus",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_jsonKeyFilePath"),
					},
					{
						Name: "token",
						ResourceRef: []config.ResourceReference{
							{
								Name:    "cumulusSystemTrustSecretName",
								Type:    "systemTrustSecret",
								Default: "cumulus",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_token"),
					},
					{
						Name:        "pipelineId",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_pipelineId"),
					},
					{
						Name:        "stepResultType",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `general`,
					},
					{
						Name:        "subFolderPath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_subFolderPath"),
					},
					{
						Name:        "targetPath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEP"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_targetPath"),
					},
					{
						Name: "version",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "artifactVersion",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_version"),
					},
					{
						Name: "gitHeadCommitId",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/headCommitId",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitHeadCommitId"),
					},
					{
						Name:        "useCommitIdForCumulus",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
				},
			},
		},
	}
	return theMetaData
}
