// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/piperenv"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/spf13/cobra"
)

type sapDwCStageReleaseOptions struct {
	AppName                         string                   `json:"appName,omitempty"`
	Apps                            []map[string]interface{} `json:"apps,omitempty"`
	ArtifactFilesToUpload           []string                 `json:"artifactFilesToUpload,omitempty"`
	ArtifactPattern                 string                   `json:"artifactPattern,omitempty"`
	Artifacts                       []map[string]interface{} `json:"artifacts,omitempty"`
	ArtifactType                    string                   `json:"artifactType,omitempty" validate:"possible-values=java maven maven-mta mta dockerbuild-releaseMetadata helm"`
	ArtifactURLs                    []string                 `json:"artifactURLs,omitempty"`
	ArtifactVersion                 string                   `json:"artifactVersion,omitempty"`
	CliPath                         string                   `json:"cliPath,omitempty"`
	DeriveAdditionalDownloadURLs    []map[string]interface{} `json:"deriveAdditionalDownloadURLs,omitempty"`
	DownloadedArchivesPath          string                   `json:"downloadedArchivesPath,omitempty"`
	GatewayCertificatePath          string                   `json:"gatewayCertificatePath,omitempty"`
	GatewayURL                      string                   `json:"gatewayURL,omitempty"`
	GithubToken                     string                   `json:"githubToken,omitempty"`
	HelmChartDirectory              string                   `json:"helmChartDirectory,omitempty"`
	HelmChartURL                    string                   `json:"helmChartUrl,omitempty"`
	HelmValues                      []string                 `json:"helmValues,omitempty"`
	MtarFilePath                    string                   `json:"mtarFilePath,omitempty"`
	MtarUIPath                      string                   `json:"mtarUIPath,omitempty"`
	OverwriteHelmDockerImage        bool                     `json:"overwriteHelmDockerImage,omitempty"`
	ProjectName                     string                   `json:"projectName,omitempty"`
	PromotedDockerImage             string                   `json:"promotedDockerImage,omitempty"`
	Repository                      string                   `json:"repository,omitempty"`
	RequiredSuccessfulStages        []string                 `json:"requiredSuccessfulStages,omitempty"`
	ResourceName                    string                   `json:"resourceName,omitempty"`
	StagesToWatch                   []string                 `json:"stagesToWatch,omitempty"`
	StageWatchPolicy                string                   `json:"stageWatchPolicy,omitempty" validate:"possible-values=overallSuccess subsetSuccess atLeastOneSuccessfulDeployment alwaysPass"`
	ThemistoInstanceCertificatePath string                   `json:"themistoInstanceCertificatePath,omitempty"`
	ThemistoInstanceURL             string                   `json:"themistoInstanceURL,omitempty"`
	UiUploadBasePath                string                   `json:"uiUploadBasePath,omitempty"`
	UploadMetadata                  []string                 `json:"uploadMetadata,omitempty"`
	UploadType                      string                   `json:"uploadType,omitempty" validate:"possible-values=service ui orbit"`
	UseCertLogin                    bool                     `json:"useCertLogin,omitempty"`
	WatchResourceOfInterest         bool                     `json:"watchResourceOfInterest,omitempty"`
	VaultBasePath                   string                   `json:"vaultBasePath,omitempty"`
	VaultPipelineName               string                   `json:"vaultPipelineName,omitempty"`
	PipelineID                      string                   `json:"pipelineID,omitempty"`
	CumulusPipelineRunKey           string                   `json:"cumulusPipelineRunKey,omitempty"`
}

type sapDwCStageReleaseCommonPipelineEnvironment struct {
	custom struct {
		dwcUploadedArtifactID  string
		dwcUploadedArtifactIDs []string
	}
}

func (p *sapDwCStageReleaseCommonPipelineEnvironment) persist(path, resourceName string) {
	content := []struct {
		category string
		name     string
		value    interface{}
	}{
		{category: "custom", name: "dwcUploadedArtifactId", value: p.custom.dwcUploadedArtifactID},
		{category: "custom", name: "dwcUploadedArtifactIds", value: p.custom.dwcUploadedArtifactIDs},
	}

	errCount := 0
	for _, param := range content {
		err := piperenv.SetResourceParameter(path, resourceName, filepath.Join(param.category, param.name), param.value)
		if err != nil {
			log.Entry().WithError(err).Error("Error persisting piper environment.")
			errCount++
		}
	}
	if errCount > 0 {
		log.Entry().Error("failed to persist Piper environment")
	}
}

// SapDwCStageReleaseCommand This step provides the capability to upload services and UIs to [Deploy with Confidence (DwC)](https://pages.github.tools.sap/deploy-with-confidence/solar-system/).
func SapDwCStageReleaseCommand() *cobra.Command {
	const STEP_NAME = "sapDwCStageRelease"

	metadata := sapDwCStageReleaseMetadata()
	var stepConfig sapDwCStageReleaseOptions
	var startTime time.Time
	var commonPipelineEnvironment sapDwCStageReleaseCommonPipelineEnvironment
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapDwCStageReleaseCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "This step provides the capability to upload services and UIs to [Deploy with Confidence (DwC)](https://pages.github.tools.sap/deploy-with-confidence/solar-system/).",
		Long: `You are also able to watch the resulting Vector Deployments on specific Stages to set your pipeline result to success/error.

To use this step it is necessary that you already have an onboarded DwC instance. If you don't have one yet feel free to follow our [onboarding guide](https://pages.github.tools.sap/deploy-with-confidence/solar-system/onboarding/).

!!! note "Support channels"
    If you are facing any problem, want to raise a bug or a feature request, please use our support channels to get in touch with us.
    You can use one of the following channels:

    * [#sap-dwc](https://sap-btp.slack.com/archives/C0115K14FMG): Slack community channel for discussion, questions, etc.
    * [GitHub issues](https://github.tools.sap/deploy-with-confidence/issues/issues/new/choose): GitHub issue repository to report bugs and request features`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.GatewayCertificatePath)
			log.RegisterSecret(stepConfig.GithubToken)
			log.RegisterSecret(stepConfig.ThemistoInstanceCertificatePath)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				commonPipelineEnvironment.persist(piperOsCmd.GeneralConfig.EnvRootPath, "commonPipelineEnvironment")
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapDwCStageRelease(stepConfig, &stepTelemetryData, &commonPipelineEnvironment)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapDwCStageReleaseFlags(createSapDwCStageReleaseCmd, &stepConfig)
	return createSapDwCStageReleaseCmd
}

func addSapDwCStageReleaseFlags(cmd *cobra.Command, stepConfig *sapDwCStageReleaseOptions) {
	cmd.Flags().StringVar(&stepConfig.AppName, "appName", os.Getenv("PIPER_appName"), "Defines the name of the application to be uploaded and deployed. The app name is also used as an identifier for routing both inbound services and [Jupiter](https://pages.github.tools.sap/deploy-with-confidence/solar-system/explanations/components#jupiter).")

	cmd.Flags().StringSliceVar(&stepConfig.ArtifactFilesToUpload, "artifactFilesToUpload", []string{`manifest.yml`, `.dwc`, `helm`, `cf`}, "List of glob file patterns. Matched files and folders are uploaded to Themisto. Be aware that for patterns like `folder-x/**` only the subfolders of `folder-x` are uploaded and **not** the folder `folder-x` itself. So if you want to use [landscape-specific deployment variables](https://pages.github.tools.sap/deploy-with-confidence/solar-system/references/deployment_variables/) you have to use `.dwc` instead of `.dwc/**`.")
	cmd.Flags().StringVar(&stepConfig.ArtifactPattern, "artifactPattern", os.Getenv("PIPER_artifactPattern"), "Regex to identify artifact URL. If multiple artifacts are promoted the artifact pattern can be used to filter promoted artifact URLs. Default artifact pattern depends on the build tool: `**/{ repository }/**/{ *.jar | *.mtar | * }`")

	cmd.Flags().StringVar(&stepConfig.ArtifactType, "artifactType", os.Getenv("PIPER_artifactType"), "Type of the built artifact. Needs to be set in case of service upload.")
	cmd.Flags().StringSliceVar(&stepConfig.ArtifactURLs, "artifactURLs", []string{}, "URLs which points to the artifacts which are promoted to Artifactory.")
	cmd.Flags().StringVar(&stepConfig.ArtifactVersion, "artifactVersion", os.Getenv("PIPER_artifactVersion"), "The version assigned by artifactPrepareVersion to the uploaded artifact.")
	cmd.Flags().StringVar(&stepConfig.CliPath, "cliPath", os.Getenv("PIPER_cliPath"), "Path that points to the DwC CLI binary. If path is specified, the latest version of the CLI will **not** be downloaded from GitHub and the specified binary will be used to execute DwC CLI commands.")

	cmd.Flags().StringVar(&stepConfig.DownloadedArchivesPath, "downloadedArchivesPath", os.Getenv("PIPER_downloadedArchivesPath"), "Path to the artifact archives downloaded by [sapDownloadArtifact](https://go.sap.corp/piper/steps/sapDownloadArtifact/).")
	cmd.Flags().StringVar(&stepConfig.GatewayCertificatePath, "gatewayCertificatePath", os.Getenv("PIPER_gatewayCertificatePath"), "File path of certificate file containing both certificate chain and key. This certificate will be used to authenticate against the DwC API Gateway. Upload this file to Vault/Jenkins credential store and the step will retrieve the path automatically. You don't have to provide the file path to it manually. Find out more about secret files in Jenkins [here](https://www.jenkins.io/doc/book/using/using-credentials/).")
	cmd.Flags().StringVar(&stepConfig.GatewayURL, "gatewayURL", `https://api.mtls.dwc.tools.sap`, "Defines the URL of the DwC API Gateway used to upload the artifact.")
	cmd.Flags().StringVar(&stepConfig.GithubToken, "githubToken", os.Getenv("PIPER_githubToken"), "GitHub personal access token (PAT) with at least public access (default). If you don't know how to create a PAT take a look at [GitHub's official documentation](https://docs.github.com/en/enterprise-server@3.5/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).")
	cmd.Flags().StringVar(&stepConfig.HelmChartDirectory, "helmChartDirectory", `helm`, "Path to the Helm chart directory.")
	cmd.Flags().StringVar(&stepConfig.HelmChartURL, "helmChartUrl", os.Getenv("PIPER_helmChartUrl"), "URL of the Helm chart built by [helmExecute](https://go.sap.corp/piper/steps/helmExecute/).")
	cmd.Flags().StringSliceVar(&stepConfig.HelmValues, "helmValues", []string{}, "List of helm values as YAML file reference (as per helm parameter description for `-f` / `--values`).\nThe step deep-merges defined YAML files, with later sources taking priority over earlier ones.\nThe resulting YAML file will be saved to `helm/values.yaml`. It will overwrite the file if already exists.\n\nIf no file is specified the step will just consider the default values file: `helm/values.yaml`.")
	cmd.Flags().StringVar(&stepConfig.MtarFilePath, "mtarFilePath", os.Getenv("PIPER_mtarFilePath"), "Path to the mtar archive")
	cmd.Flags().StringVar(&stepConfig.MtarUIPath, "mtarUIPath", `app`, "Specifies the path to the UI modules in the mtar archive. This parameter is **mandatory** if one of the artifacts sets `extractFromMTA` to `true` and the UI files are in a subdirectory inside the mtar archive.")
	cmd.Flags().BoolVar(&stepConfig.OverwriteHelmDockerImage, "overwriteHelmDockerImage", false, "Indicates whether the docker image and tag should be templated into the helm chart before uploading.\nThis might be useful if you don't want to use the `latest` tag but the actual version of the promoted docker image.\nThe step retrieves the `artifactVersion` from the `artifactPrepareVersion` step and uses it as the tag if `overwriteHelmDockerImage` is set to `true`.\n\nThe step will overwrite the `image.repository` and `image.tag` values in the final `<helmChartDirectory>/values.yaml` file (see parameter [`helmChartDirectory`](#helmchartdirectory)).\nThe final `<helmChartDirectory>/values.yaml` file is the result of the deep-merge of the value files provided by the `helmValues` parameter.\nMore about the `helmValues` parameter (and its merge behaviour) can be found [here](#helmvalues).")
	cmd.Flags().StringVar(&stepConfig.ProjectName, "projectName", os.Getenv("PIPER_projectName"), "Defines the name of the DwC Project where the artifact should be uploaded to.")
	cmd.Flags().StringVar(&stepConfig.PromotedDockerImage, "promotedDockerImage", os.Getenv("PIPER_promotedDockerImage"), "Name of promoted docker image as result of the promotion stage (e.g. `deploy-releases-hyperspace-docker.common.repositories.cloud.sap/your/image`). Optionally, you can add a tag. If the specified docker image does not contain a tag the `artifactVersion` will be used as tag.\n\nIf `uploadType` is `service`, this parameter is **mandatory** for `artifactType` `dockerbuild-releaseMetadata` and `helm`. If `uploadType` is `orbit` this parameter is **mandatory** as well.")
	cmd.Flags().StringVar(&stepConfig.Repository, "repository", `common.repositories.cloud.sap`, "Repository where the artifact is uploaded to. Needs to be set without `https://`. Does not take affect in case `artifactPattern` is defined.")
	cmd.Flags().StringSliceVar(&stepConfig.RequiredSuccessfulStages, "requiredSuccessfulStages", []string{}, "List of stages where the artifact deployment needs to be successful to succeed the step. Needs to be specified if `stageWatchPolicy` is set to `subsetSuccess` and will be ignored if `stageWatchPolicy` is unequal `subsetSuccess`. However, the step waits until the **vector** deployment is completed and does not terminate if the artifact deployment is completed earlier.")
	cmd.Flags().StringVar(&stepConfig.ResourceName, "resourceName", os.Getenv("PIPER_resourceName"), "Identifier of the service for Themisto. If not stated explicitly, the `resourceName` defaults to `<githubInstance>/<githubRepository>/<branch>`. The `resourceName` is also displayed by Amalthea e.g. in the stage overview.")
	cmd.Flags().StringSliceVar(&stepConfig.StagesToWatch, "stagesToWatch", []string{}, "List of stages to be watched. If no stage is defined the step will be successful after uploading the artifact to Themisto. The step will not validate if Vector Deployments are successful. If you specify the * selector as a single array element all stages for which a promotion was triggered will be watched.")
	cmd.Flags().StringVar(&stepConfig.StageWatchPolicy, "stageWatchPolicy", `overallSuccess`, "Defines the stage watch policy. Just relevant if `stagesToWatch` is set.")
	cmd.Flags().StringVar(&stepConfig.ThemistoInstanceCertificatePath, "themistoInstanceCertificatePath", os.Getenv("PIPER_themistoInstanceCertificatePath"), "File path of certificate file containing both certificate chain and key. Upload this file to Vault/Jenkins credential store and the step will retrieve the path automatically. You don't have to provide the file path to it manually. Find out more about secret files in Jenkins [here](https://www.jenkins.io/doc/book/using/using-credentials/).")
	cmd.Flags().StringVar(&stepConfig.ThemistoInstanceURL, "themistoInstanceURL", os.Getenv("PIPER_themistoInstanceURL"), "URL of targeted Themisto instance.")
	cmd.Flags().StringVar(&stepConfig.UiUploadBasePath, "uiUploadBasePath", ``, "Defines the base path where the specified artifact files are uploaded to. If unset the base path will be set to `webapps/<appName>`.")
	cmd.Flags().StringSliceVar(&stepConfig.UploadMetadata, "uploadMetadata", []string{}, "Custom upload metadata that is attached to your uploaded artifact. The format needs to be: `key=value`. If your value is an object, please provide it as string encoded JSON.")
	cmd.Flags().StringVar(&stepConfig.UploadType, "uploadType", os.Getenv("PIPER_uploadType"), "Artifact upload type determines how to proceed with the artifact and how to handle the upload and deployment.")
	cmd.Flags().BoolVar(&stepConfig.UseCertLogin, "useCertLogin", false, "Indicates whether the DwC CLI should use a certificate for authentication (only relevant for GitHub Actions pipelines). If set to `false`, OIDC authentication is used.")
	cmd.Flags().BoolVar(&stepConfig.WatchResourceOfInterest, "watchResourceOfInterest", true, "If set to `true`, **only** the logs of the uploaded artifact (resource of interest or ROI) are streamed to console output not the logs from the whole vector deployment and the deployment watching reflects the artifact deployment state of the ROI.\nIf this option is set to `false` the deployment watching reflects the vector deployment state.\nHowever, the step waits until the **vector** deployment is completed and does not terminate if the artifact deployment is completed earlier.\nThis means that the deployment watching for the stage returns an error if the vector deployment times out (after 60 minutes), even if the artifact deployment of the ROI is successful.\nBesides the deployment watching result, the exit code of the step depends on the configuration of `stageWatchPolicy`.\nFurthermore, the step only waits for the vector deployment to finish, not for any migrations or the activation of the vector.\n")
	cmd.Flags().StringVar(&stepConfig.VaultBasePath, "vaultBasePath", os.Getenv("PIPER_vaultBasePath"), "the vault base path used for cumulus integration")
	cmd.Flags().StringVar(&stepConfig.VaultPipelineName, "vaultPipelineName", os.Getenv("PIPER_vaultPipelineName"), "the vault pipeline name used for cumulus integration")
	cmd.Flags().StringVar(&stepConfig.PipelineID, "pipelineID", os.Getenv("PIPER_pipelineID"), "the cumulus pipeline id used for cumulus integration")
	cmd.Flags().StringVar(&stepConfig.CumulusPipelineRunKey, "cumulusPipelineRunKey", os.Getenv("PIPER_cumulusPipelineRunKey"), "the key identifying this specific pipeline run")

	cmd.Flags().MarkDeprecated("themistoInstanceCertificatePath", "Upload via Themisto is deprecated. Please use `gatewayCertificatePath` instead.")
	cmd.Flags().MarkDeprecated("themistoInstanceURL", "Upload via Themisto is deprecated. Please use the DwC API Gateway instead. To do so, please use `gatewayURL`.")
}

// retrieve step metadata
func sapDwCStageReleaseMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapDwCStageRelease",
			Aliases:     []config.Alias{},
			Description: "This step provides the capability to upload services and UIs to [Deploy with Confidence (DwC)](https://pages.github.tools.sap/deploy-with-confidence/solar-system/).",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "githubTokenCredentialsId", Description: "Jenkins 'Secret text' credentials ID containing token to authenticate to GitHub.", Type: "jenkins"},
					{Name: "themistoInstanceCertificateCredentialsId", Description: "Jenkins 'Secret File' credentials ID containing both the Themisto instance certificate chain and key.", Type: "jenkins", Aliases: []config.Alias{{Name: "themistoCredentialsId", Deprecated: false}}},
					{Name: "gatewayCertificateCredentialsId", Description: "Jenkins 'Secret File' credentials ID containing both the Dwc Gateway certificate chain and key.", Type: "jenkins", Aliases: []config.Alias{{Name: "gatewayCredentialsId", Deprecated: false}, {Name: "dwcGatewayCredentialsId", Deprecated: false}}},
				},
				Parameters: []config.StepParameters{
					{
						Name:        "appName",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "appname"}, {Name: "dwcAppName"}, {Name: "dwcAppname"}},
						Default:     os.Getenv("PIPER_appName"),
					},
					{
						Name:        "apps",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STEPS"},
						Type:        "[]map[string]interface{}",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcApps"}},
						Default:     []map[string]interface{}{},
					},
					{
						Name:        "artifactFilesToUpload",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "filesToUpload"}, {Name: "dwcFilesToUpload"}, {Name: "dwcArtifactFilesToUpload"}},
						Default:     []string{`manifest.yml`, `.dwc`, `helm`, `cf`},
					},
					{
						Name:        "artifactPattern",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_artifactPattern"),
					},
					{
						Name:        "artifacts",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STEPS"},
						Type:        "[]map[string]interface{}",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcArtifacts"}},
						Default:     []map[string]interface{}{},
					},
					{
						Name:        "artifactType",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_artifactType"),
					},
					{
						Name: "artifactURLs",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/promotedArtifactUrls",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "[]string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   []string{},
					},
					{
						Name: "artifactVersion",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "artifactVersion",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_artifactVersion"),
					},
					{
						Name:        "cliPath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcCLIPath"}},
						Default:     os.Getenv("PIPER_cliPath"),
					},
					{
						Name:        "deriveAdditionalDownloadURLs",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "[]map[string]interface{}",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcDeriveAdditionalDownloadURLs"}},
					},
					{
						Name: "downloadedArchivesPath",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/downloadTargetPath",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_downloadedArchivesPath"),
					},
					{
						Name: "gatewayCertificatePath",
						ResourceRef: []config.ResourceReference{
							{
								Name: "gatewayCertificateCredentialsId",
								Type: "secret",
							},

							{
								Name:    "dwcCertificateCredentialsVaultSecretName",
								Type:    "vaultSecretFile",
								Default: "dwc",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{{Name: "certificate"}, {Name: "dwcClientCert"}, {Name: "dwcGatewayCertificate"}, {Name: "gatewayCertificate"}},
						Default:   os.Getenv("PIPER_gatewayCertificatePath"),
					},
					{
						Name:        "gatewayURL",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "apiGatewayURL"}, {Name: "dwcApiUrl"}, {Name: "dwcGatewayURL"}, {Name: "dwcGatewayUrl"}},
						Default:     `https://api.mtls.dwc.tools.sap`,
					},
					{
						Name: "githubToken",
						ResourceRef: []config.ResourceReference{
							{
								Name: "githubTokenCredentialsId",
								Type: "secret",
							},

							{
								Name:    "githubVaultSecretName",
								Type:    "vaultSecret",
								Default: "github-tools",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{{Name: "githubAccessToken"}, {Name: "githubPAT"}, {Name: "access_token"}},
						Default:   os.Getenv("PIPER_githubToken"),
					},
					{
						Name:        "helmChartDirectory",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcHelmChartDirectory"}},
						Default:     `helm`,
					},
					{
						Name: "helmChartUrl",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/helmChartUrl",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_helmChartUrl"),
					},
					{
						Name:        "helmValues",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     []string{},
					},
					{
						Name: "mtarFilePath",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "mtarFilePath",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_mtarFilePath"),
					},
					{
						Name:        "mtarUIPath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcMtarUIPath"}},
						Default:     `app`,
					},
					{
						Name:        "overwriteHelmDockerImage",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcOverwriteHelmDockerImage"}},
						Default:     false,
					},
					{
						Name:        "projectName",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcProjectName"}},
						Default:     os.Getenv("PIPER_projectName"),
					},
					{
						Name:        "promotedDockerImage",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dockerImage"}, {Name: "dwcPromotedDockerImage"}},
						Default:     os.Getenv("PIPER_promotedDockerImage"),
					},
					{
						Name:        "repository",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "promotedRegistry"}},
						Default:     `common.repositories.cloud.sap`,
					},
					{
						Name:        "requiredSuccessfulStages",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcRequiredSuccessfulStages"}},
						Default:     []string{},
					},
					{
						Name:        "resourceName",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcResourceName"}},
						Default:     os.Getenv("PIPER_resourceName"),
					},
					{
						Name:        "stagesToWatch",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "watchDeployments"}, {Name: "deploymentTargets"}, {Name: "dwcStagesToWatch"}},
						Default:     []string{},
					},
					{
						Name:        "stageWatchPolicy",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcStageWatchPolicy"}},
						Default:     `overallSuccess`,
					},
					{
						Name: "themistoInstanceCertificatePath",
						ResourceRef: []config.ResourceReference{
							{
								Name: "themistoInstanceCertificateCredentialsId",
								Type: "secret",
							},

							{
								Name:    "themistoInstanceCertificateCredentialsVaultSecretName",
								Type:    "vaultSecretFile",
								Default: "themisto",
							},
						},
						Scope:              []string{"PARAMETERS"},
						Type:               "string",
						Mandatory:          false,
						Aliases:            []config.Alias{{Name: "certificate"}, {Name: "themistoCertificate"}},
						Default:            os.Getenv("PIPER_themistoInstanceCertificatePath"),
						DeprecationMessage: "Upload via Themisto is deprecated. Please use `gatewayCertificatePath` instead.",
					},
					{
						Name:               "themistoInstanceURL",
						ResourceRef:        []config.ResourceReference{},
						Scope:              []string{"PARAMETERS", "STAGES", "STEPS", "GENERAL"},
						Type:               "string",
						Mandatory:          false,
						Aliases:            []config.Alias{{Name: "themistoUrl"}},
						Default:            os.Getenv("PIPER_themistoInstanceURL"),
						DeprecationMessage: "Upload via Themisto is deprecated. Please use the DwC API Gateway instead. To do so, please use `gatewayURL`.",
					},
					{
						Name:        "uiUploadBasePath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcUIUploadBasePath"}},
						Default:     ``,
					},
					{
						Name:        "uploadMetadata",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcUploadMetadata"}, {Name: "customMetadata"}, {Name: "metadata"}},
						Default:     []string{},
					},
					{
						Name:        "uploadType",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcUploadType"}},
						Default:     os.Getenv("PIPER_uploadType"),
					},
					{
						Name:        "useCertLogin",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS", "GENERAL"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dwcUseCertLogin"}},
						Default:     false,
					},
					{
						Name:        "watchResourceOfInterest",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "useROI"}, {Name: "watchROI"}, {Name: "dwcWatchResourceOfInterest"}, {Name: "dwcWatchROI"}, {Name: "dwcUseROI"}},
						Default:     true,
					},
					{
						Name:        "vaultBasePath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS", "GENERAL"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_vaultBasePath"),
					},
					{
						Name:        "vaultPipelineName",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS", "GENERAL"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_vaultPipelineName"),
					},
					{
						Name: "pipelineID",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/cumulusPipelineID",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS", "GENERAL"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_pipelineID"),
					},
					{
						Name: "cumulusPipelineRunKey",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/cumulusPipelineRunKey",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS", "GENERAL"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_cumulusPipelineRunKey"),
					},
				},
			},
			Containers: []config.Container{
				{Image: "alpine:3", EnvVars: []config.EnvVar{{Name: "DWC_CONFIG", Value: "/tmp/.dwc"}}},
			},
			Outputs: config.StepOutputs{
				Resources: []config.StepResources{
					{
						Name: "commonPipelineEnvironment",
						Type: "piperEnvironment",
						Parameters: []map[string]interface{}{
							{"name": "custom/dwcUploadedArtifactId"},
							{"name": "custom/dwcUploadedArtifactIds", "type": "[]string"},
						},
					},
				},
			},
		},
	}
	return theMetaData
}
