// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/spf13/cobra"
)

type sapDasterExecuteScanOptions struct {
	ClientID        string                 `json:"clientId,omitempty"`
	ClientSecret    string                 `json:"clientSecret,omitempty"`
	UserCredentials string                 `json:"userCredentials,omitempty"`
	DasterToken     string                 `json:"dasterToken,omitempty"`
	User            string                 `json:"user,omitempty"`
	Password        string                 `json:"password,omitempty"`
	TargetURL       string                 `json:"targetUrl,omitempty"`
	MaxRetries      int                    `json:"maxRetries,omitempty"`
	RetryDelay      int                    `json:"retryDelay,omitempty"`
	OAuthGrantType  string                 `json:"oAuthGrantType,omitempty"`
	OAuthSource     string                 `json:"oAuthSource,omitempty"`
	OAuthServiceURL string                 `json:"oAuthServiceUrl,omitempty"`
	Synchronous     bool                   `json:"synchronous,omitempty"`
	ScanType        string                 `json:"scanType,omitempty" validate:"possible-values=fioriDASTScan"`
	Settings        map[string]interface{} `json:"settings,omitempty"`
	DeleteScan      bool                   `json:"deleteScan,omitempty"`
	ServiceURL      string                 `json:"serviceUrl,omitempty"`
	Thresholds      map[string]interface{} `json:"thresholds,omitempty"`
	Verbose         bool                   `json:"verbose,omitempty"`
}

// SapDasterExecuteScanCommand Dynamic Application Security Testing (DAST)
func SapDasterExecuteScanCommand() *cobra.Command {
	const STEP_NAME = "sapDasterExecuteScan"

	metadata := sapDasterExecuteScanMetadata()
	var stepConfig sapDasterExecuteScanOptions
	var startTime time.Time
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapDasterExecuteScanCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "Dynamic Application Security Testing (DAST)",
		Long: `The name DASTer is derived from Dynamic Application Security Testing. As the name implies, the tool targets to provide black-box security testing capabilities for your solutions in an automated fashion.
DASTer itself ships with a [Swagger based frontend](https://daster.tools.sap/api-spec/viewer/) and a [Web UI](https://app.daster.tools.sap/ui5/) to generate tokens
required to record your consent and to authenticate. Please see the [documentation](https://github.wdf.sap.corp/pages/Security-Testing/doc/daster/) for
background information about the tool, its usage scenarios and channels to report problems.`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.ClientID)
			log.RegisterSecret(stepConfig.ClientSecret)
			log.RegisterSecret(stepConfig.UserCredentials)
			log.RegisterSecret(stepConfig.DasterToken)
			log.RegisterSecret(stepConfig.User)
			log.RegisterSecret(stepConfig.Password)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapDasterExecuteScan(stepConfig, &stepTelemetryData)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapDasterExecuteScanFlags(createSapDasterExecuteScanCmd, &stepConfig)
	return createSapDasterExecuteScanCmd
}

func addSapDasterExecuteScanFlags(cmd *cobra.Command, stepConfig *sapDasterExecuteScanOptions) {
	cmd.Flags().StringVar(&stepConfig.ClientID, "clientId", os.Getenv("PIPER_clientId"), "client id used to fetch an oAuth token for FioriDAST service testing.")
	cmd.Flags().StringVar(&stepConfig.ClientSecret, "clientSecret", os.Getenv("PIPER_clientSecret"), "client secret used to fetch an oAuth token for FioriDAST service testing.")
	cmd.Flags().StringVar(&stepConfig.UserCredentials, "userCredentials", os.Getenv("PIPER_userCredentials"), "Access token for the scanning application. Example: `LOGIN:PASSWORD`.")
	cmd.Flags().StringVar(&stepConfig.DasterToken, "dasterToken", os.Getenv("PIPER_dasterToken"), "DASTer token. It must be generated for each system using a self-service application.")
	cmd.Flags().StringVar(&stepConfig.User, "user", os.Getenv("PIPER_user"), "Username for authentication in the scanning application.")
	cmd.Flags().StringVar(&stepConfig.Password, "password", os.Getenv("PIPER_password"), "Password for authentication in the scanning application.")
	cmd.Flags().StringVar(&stepConfig.TargetURL, "targetUrl", os.Getenv("PIPER_targetUrl"), "URL of the scanning application.")
	cmd.Flags().IntVar(&stepConfig.MaxRetries, "maxRetries", 3, "Number of retries to attempt in case of HTTP connection instability.")
	cmd.Flags().IntVar(&stepConfig.RetryDelay, "retryDelay", 30, "Delay in seconds before retrying an HTTP request.")
	cmd.Flags().StringVar(&stepConfig.OAuthGrantType, "oAuthGrantType", `client_credentials`, "Grant type used for fetching the oAuth token.")
	cmd.Flags().StringVar(&stepConfig.OAuthSource, "oAuthSource", `uaa.resource`, "Source used to fetch the oAuth token.")
	cmd.Flags().StringVar(&stepConfig.OAuthServiceURL, "oAuthServiceUrl", os.Getenv("PIPER_oAuthServiceUrl"), "URL to the XSUAA used for fetching the oAuth token.")
	cmd.Flags().BoolVar(&stepConfig.Synchronous, "synchronous", true, "Whether to use the step in synchronous or asynchronous mode.")
	cmd.Flags().StringVar(&stepConfig.ScanType, "scanType", `fioriDASTScan`, "Type of DASTer scan to trigger, corresponding to the API endpoints (e.g., 'basicScan').")

	cmd.Flags().BoolVar(&stepConfig.DeleteScan, "deleteScan", true, "Whether to delete the scan after completion. Only supported for `fioriDASTScan`.")
	cmd.Flags().StringVar(&stepConfig.ServiceURL, "serviceUrl", `https://daster.tools.sap/`, "URL to DASTer.")

	cmd.Flags().BoolVar(&stepConfig.Verbose, "verbose", false, "Enable verbose logging.")

	cmd.MarkFlagRequired("clientId")
	cmd.MarkFlagRequired("clientSecret")
	cmd.MarkFlagRequired("userCredentials")
	cmd.MarkFlagRequired("dasterToken")
	cmd.MarkFlagRequired("user")
	cmd.MarkFlagRequired("password")
}

// retrieve step metadata
func sapDasterExecuteScanMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapDasterExecuteScan",
			Aliases:     []config.Alias{},
			Description: "Dynamic Application Security Testing (DAST)",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "oAuthCredentialsId", Description: "ID referencing user/password credentials to fetch an oAuth token for FioriDAST service testing. Encode `client_id` as username and `client_secret` as password.", Type: "jenkins"},
					{Name: "dasterTokenCredentialsId", Description: "ID referencing a secret text credential to fetch a DASTer token.", Type: "jenkins"},
					{Name: "userCredentialsId", Description: "ID referencing a secret text credential for authentication in the scanning application.", Type: "jenkins"},
					{Name: "targetAuthCredentialsId", Description: "ID referencing user/password credentials for authentication in the scanning application.", Type: "jenkins"},
				},
				Resources: []config.StepResources{
					{Name: "commonPipelineEnvironment"},
					{Name: "buildDescriptor", Type: "stash"},
					{Name: "tests", Type: "stash"},
				},
				Parameters: []config.StepParameters{
					{
						Name: "clientId",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "oAuthCredentialsId",
								Param: "clientId",
								Type:  "secret",
							},

							{
								Name:    "dasterVaultSecretName",
								Type:    "vaultSecret",
								Default: "daster",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_clientId"),
					},
					{
						Name: "clientSecret",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "oAuthCredentialsId",
								Param: "clientSecret",
								Type:  "secret",
							},

							{
								Name:    "dasterVaultSecretName",
								Type:    "vaultSecret",
								Default: "daster",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_clientSecret"),
					},
					{
						Name: "userCredentials",
						ResourceRef: []config.ResourceReference{
							{
								Name: "userCredentialsId",
								Type: "secret",
							},

							{
								Name:    "dasterVaultSecretName",
								Type:    "vaultSecret",
								Default: "userCredentialsId",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_userCredentials"),
					},
					{
						Name: "dasterToken",
						ResourceRef: []config.ResourceReference{
							{
								Name: "dasterTokenCredentialsId",
								Type: "secret",
							},

							{
								Name:    "dasterVaultSecretName",
								Type:    "vaultSecret",
								Default: "daster",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_dasterToken"),
					},
					{
						Name: "user",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "targetAuthCredentialsId",
								Param: "user",
								Type:  "secret",
							},

							{
								Name:    "dasterVaultSecretName",
								Type:    "vaultSecret",
								Default: "daster",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_user"),
					},
					{
						Name: "password",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "targetAuthCredentialsId",
								Param: "password",
								Type:  "secret",
							},

							{
								Name:    "dasterVaultSecretName",
								Type:    "vaultSecret",
								Default: "daster",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_password"),
					},
					{
						Name:        "targetUrl",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_targetUrl"),
					},
					{
						Name:        "maxRetries",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "int",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     3,
					},
					{
						Name:        "retryDelay",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "int",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     30,
					},
					{
						Name:        "oAuthGrantType",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `client_credentials`,
					},
					{
						Name:        "oAuthSource",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `uaa.resource`,
					},
					{
						Name:        "oAuthServiceUrl",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_oAuthServiceUrl"),
					},
					{
						Name:        "synchronous",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     true,
					},
					{
						Name:        "scanType",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `fioriDASTScan`,
					},
					{
						Name:        "settings",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "map[string]interface{}",
						Mandatory:   false,
						Aliases:     []config.Alias{},
					},
					{
						Name:        "deleteScan",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     true,
					},
					{
						Name:        "serviceUrl",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `https://daster.tools.sap/`,
					},
					{
						Name:        "thresholds",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "map[string]interface{}",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default: map[string]interface{}{
							"high": 0,
						},
					},
					{
						Name:        "verbose",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
				},
			},
			Containers: []config.Container{
				{},
			},
		},
	}
	return theMetaData
}
