// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/piperenv"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/spf13/cobra"
)

type sapDownloadArtifactOptions struct {
	ArtifactoryToken                 string                   `json:"artifactoryToken,omitempty"`
	StagingServiceRepositoryPassword string                   `json:"stagingServiceRepositoryPassword,omitempty"`
	StagingServiceRepositoryUser     string                   `json:"stagingServiceRepositoryUser,omitempty"`
	ArtifactID                       string                   `json:"artifactId,omitempty"`
	BuildTool                        string                   `json:"buildTool,omitempty"`
	FilePath                         string                   `json:"filePath,omitempty"`
	FromStaging                      bool                     `json:"fromStaging,omitempty"`
	GlobalSettingsFile               string                   `json:"globalSettingsFile,omitempty"`
	GroupID                          string                   `json:"groupId,omitempty"`
	M2Path                           string                   `json:"m2Path,omitempty"`
	MaxRetries                       int                      `json:"maxRetries,omitempty"`
	Packaging                        string                   `json:"packaging,omitempty"`
	ProjectSettingsFile              string                   `json:"projectSettingsFile,omitempty"`
	RepositoryURL                    string                   `json:"repositoryUrl,omitempty"`
	Timeout                          int                      `json:"timeout,omitempty"`
	Version                          string                   `json:"version,omitempty"`
	ArtifactDownloadURLs             []string                 `json:"artifactDownloadUrls,omitempty"`
	ArtifactStagingDownloadURLs      []string                 `json:"artifactStagingDownloadUrls,omitempty"`
	ArtifactWithDependencies         bool                     `json:"artifactWithDependencies,omitempty"`
	MtarPublishedURL                 string                   `json:"mtarPublishedUrl,omitempty"`
	ExtractPackage                   bool                     `json:"extractPackage,omitempty"`
	Artifacts                        []map[string]interface{} `json:"artifacts,omitempty"`
	HelmChartURL                     string                   `json:"helmChartUrl,omitempty"`
	HelmStagingRepositoryPassword    string                   `json:"helmStagingRepositoryPassword,omitempty"`
	HelmStagingRepositoryUsername    string                   `json:"helmStagingRepositoryUsername,omitempty"`
	TargetPath                       string                   `json:"targetPath,omitempty"`
}

type sapDownloadArtifactCommonPipelineEnvironment struct {
	custom struct {
		localHelmChartPath string
		downloadTargetPath string
	}
}

func (p *sapDownloadArtifactCommonPipelineEnvironment) persist(path, resourceName string) {
	content := []struct {
		category string
		name     string
		value    interface{}
	}{
		{category: "custom", name: "localHelmChartPath", value: p.custom.localHelmChartPath},
		{category: "custom", name: "downloadTargetPath", value: p.custom.downloadTargetPath},
	}

	errCount := 0
	for _, param := range content {
		err := piperenv.SetResourceParameter(path, resourceName, filepath.Join(param.category, param.name), param.value)
		if err != nil {
			log.Entry().WithError(err).Error("Error persisting piper environment.")
			errCount++
		}
	}
	if errCount > 0 {
		log.Entry().Error("failed to persist Piper environment")
	}
}

// SapDownloadArtifactCommand This step allows downloading artifacts from SAP's Nexus infrastructure
func SapDownloadArtifactCommand() *cobra.Command {
	const STEP_NAME = "sapDownloadArtifact"

	metadata := sapDownloadArtifactMetadata()
	var stepConfig sapDownloadArtifactOptions
	var startTime time.Time
	var commonPipelineEnvironment sapDownloadArtifactCommonPipelineEnvironment
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapDownloadArtifactCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "This step allows downloading artifacts from SAP's Nexus infrastructure",
		Long: `With this step you can download artifacts from SAP's Nexus/Artifactory infrastructure.

It is especially suited to download files which have been run through the [staging service](https://github.wdf.sap.corp/pages/Repository-services/staging-service/).`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.ArtifactoryToken)
			log.RegisterSecret(stepConfig.StagingServiceRepositoryPassword)
			log.RegisterSecret(stepConfig.HelmStagingRepositoryPassword)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				commonPipelineEnvironment.persist(piperOsCmd.GeneralConfig.EnvRootPath, "commonPipelineEnvironment")
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapDownloadArtifact(stepConfig, &stepTelemetryData, &commonPipelineEnvironment)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapDownloadArtifactFlags(createSapDownloadArtifactCmd, &stepConfig)
	return createSapDownloadArtifactCmd
}

func addSapDownloadArtifactFlags(cmd *cobra.Command, stepConfig *sapDownloadArtifactOptions) {
	cmd.Flags().StringVar(&stepConfig.ArtifactoryToken, "artifactoryToken", os.Getenv("PIPER_artifactoryToken"), "When the DMZ artifactory repository is used to publish artifacts, then a [Reference Token](https://www.jfrog.com/confluence/display/JFROG/User+Profile#UserProfile-IdentityTokenidentitytoken) must be provided to downloaded artifacts from artifactory")
	cmd.Flags().StringVar(&stepConfig.StagingServiceRepositoryPassword, "stagingServiceRepositoryPassword", os.Getenv("PIPER_stagingServiceRepositoryPassword"), "Password for the repository created from staging services")
	cmd.Flags().StringVar(&stepConfig.StagingServiceRepositoryUser, "stagingServiceRepositoryUser", os.Getenv("PIPER_stagingServiceRepositoryUser"), "Username for the repository created from staging services")
	cmd.Flags().StringVar(&stepConfig.ArtifactID, "artifactId", os.Getenv("PIPER_artifactId"), "ArtifactId of the artifact to be downloaded from Nexus.")
	cmd.Flags().StringVar(&stepConfig.BuildTool, "buildTool", os.Getenv("PIPER_buildTool"), "Defines the tool which is used for building the artifact.")
	cmd.Flags().StringVar(&stepConfig.FilePath, "filePath", os.Getenv("PIPER_filePath"), "Defines a custom path to the descriptor file. Build tool specific defaults are used (e.g. `maven: pom.xml`, `npm: package.json`, `mta: mta.yaml`).")
	cmd.Flags().BoolVar(&stepConfig.FromStaging, "fromStaging", true, "Defines if download should consider a staged artifact (`true`) or a promoted artifact (`false`)")
	cmd.Flags().StringVar(&stepConfig.GlobalSettingsFile, "globalSettingsFile", os.Getenv("PIPER_globalSettingsFile"), "Maven only - Path to the mvn settings file that should be used as global settings file.")
	cmd.Flags().StringVar(&stepConfig.GroupID, "groupId", os.Getenv("PIPER_groupId"), "GroupId of the artifact to be downloaded from Nexus.")
	cmd.Flags().StringVar(&stepConfig.M2Path, "m2Path", os.Getenv("PIPER_m2Path"), "Maven only - Path to the location of the local repository that should be used.")
	cmd.Flags().IntVar(&stepConfig.MaxRetries, "maxRetries", 3, "Maximum number of HTTP request retries upon intermittent connection interrupts")
	cmd.Flags().StringVar(&stepConfig.Packaging, "packaging", os.Getenv("PIPER_packaging"), "Packaging of the artifact to be downloaded from Nexus. This will determine the file suffix.")
	cmd.Flags().StringVar(&stepConfig.ProjectSettingsFile, "projectSettingsFile", os.Getenv("PIPER_projectSettingsFile"), "Maven only - Path to the mvn settings file that should be used as project settings file.")
	cmd.Flags().StringVar(&stepConfig.RepositoryURL, "repositoryUrl", os.Getenv("PIPER_repositoryUrl"), "Url to the Nexus repository")
	cmd.Flags().IntVar(&stepConfig.Timeout, "timeout", 900, "Timeout in seconds until an HTTP call is forcefully terminated.")
	cmd.Flags().StringVar(&stepConfig.Version, "version", os.Getenv("PIPER_version"), "Version of the artifact to be downloaded")
	cmd.Flags().StringSliceVar(&stepConfig.ArtifactDownloadURLs, "artifactDownloadUrls", []string{}, "download urls to be used which points to the artifacts in nexus")
	cmd.Flags().StringSliceVar(&stepConfig.ArtifactStagingDownloadURLs, "artifactStagingDownloadUrls", []string{}, "download urls to be used which points to the artifacts in nexus")
	cmd.Flags().BoolVar(&stepConfig.ArtifactWithDependencies, "artifactWithDependencies", false, "when the Maven artifact is packaged with dependencies and is the artifact to be downloaded from nexus")
	cmd.Flags().StringVar(&stepConfig.MtarPublishedURL, "mtarPublishedUrl", os.Getenv("PIPER_mtarPublishedUrl"), "the url to the repository where the mtar artifact is published during staging")
	cmd.Flags().BoolVar(&stepConfig.ExtractPackage, "extractPackage", true, "when downloading an archive, run a standard extraction command and remove the original package")

	cmd.Flags().StringVar(&stepConfig.HelmChartURL, "helmChartUrl", os.Getenv("PIPER_helmChartUrl"), "URL to the Helm chart stored in the repository")
	cmd.Flags().StringVar(&stepConfig.HelmStagingRepositoryPassword, "helmStagingRepositoryPassword", os.Getenv("PIPER_helmStagingRepositoryPassword"), "Password for the repository created from staging services")
	cmd.Flags().StringVar(&stepConfig.HelmStagingRepositoryUsername, "helmStagingRepositoryUsername", os.Getenv("PIPER_helmStagingRepositoryUsername"), "Username for the repository created from staging services")
	cmd.Flags().StringVar(&stepConfig.TargetPath, "targetPath", `./`, "Path on disk where we want to save the downloaded files.")

	cmd.MarkFlagRequired("buildTool")
	cmd.MarkFlagRequired("repositoryUrl")
}

// retrieve step metadata
func sapDownloadArtifactMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapDownloadArtifact",
			Aliases:     []config.Alias{},
			Description: "This step allows downloading artifacts from SAP's Nexus infrastructure",
			Errors: []config.StepError{
				{
					Pattern:  "request to.*returned with response 401 Unauthorized",
					Message:  "Authentication failed when accessing the artifact repository. Please verify artifactoryToken in Vault",
					Category: "authentication",
				},
			},
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "artifactoryTokenCredentialsId", Description: "Jenkins credentials ID containing the DMZ artifactory API token.", Type: "jenkins"},
				},
				Parameters: []config.StepParameters{
					{
						Name: "artifactoryToken",
						ResourceRef: []config.ResourceReference{
							{
								Name: "artifactoryTokenCredentialsId",
								Type: "secret",
							},

							{
								Name:    "artifactoryTokenCredentialsVaultSecretName",
								Type:    "vaultSecret",
								Default: "common-repository",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_artifactoryToken"),
					},
					{
						Name: "stagingServiceRepositoryPassword",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/repositoryPassword",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_stagingServiceRepositoryPassword"),
					},
					{
						Name: "stagingServiceRepositoryUser",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/repositoryUsername",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_stagingServiceRepositoryUser"),
					},
					{
						Name: "artifactId",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "artifactId",
							},
						},
						Scope:     []string{"STEPS", "STAGES", "PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_artifactId"),
					},
					{
						Name:        "buildTool",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_buildTool"),
					},
					{
						Name:        "filePath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_filePath"),
					},
					{
						Name:        "fromStaging",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     true,
					},
					{
						Name:        "globalSettingsFile",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "STEPS", "STAGES", "PARAMETERS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "maven/globalSettingsFile"}},
						Default:     os.Getenv("PIPER_globalSettingsFile"),
					},
					{
						Name: "groupId",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "groupId",
							},
						},
						Scope:     []string{"STEPS", "STAGES", "PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{{Name: "group", Deprecated: true}},
						Default:   os.Getenv("PIPER_groupId"),
					},
					{
						Name:        "m2Path",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "STEPS", "STAGES", "PARAMETERS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "maven/m2Path"}},
						Default:     os.Getenv("PIPER_m2Path"),
					},
					{
						Name:        "maxRetries",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "int",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     3,
					},
					{
						Name: "packaging",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "packaging",
							},
						},
						Scope:     []string{"STEPS", "STAGES", "PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_packaging"),
					},
					{
						Name:        "projectSettingsFile",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "STEPS", "STAGES", "PARAMETERS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "maven/projectSettingsFile"}},
						Default:     os.Getenv("PIPER_projectSettingsFile"),
					},
					{
						Name: "repositoryUrl",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/repositoryUrl",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_repositoryUrl"),
					},
					{
						Name:        "timeout",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "int",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     900,
					},
					{
						Name: "version",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "artifactVersion",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{{Name: "artifactVersion"}},
						Default:   os.Getenv("PIPER_version"),
					},
					{
						Name: "artifactDownloadUrls",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/promotedArtifactUrls",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "[]string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   []string{},
					},
					{
						Name: "artifactStagingDownloadUrls",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/stagedArtifactUrls",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "[]string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   []string{},
					},
					{
						Name:        "artifactWithDependencies",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name: "mtarPublishedUrl",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/mtarPublishedUrl",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_mtarPublishedUrl"),
					},
					{
						Name:        "extractPackage",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     true,
					},
					{
						Name: "artifacts",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/artifacts",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "[]map[string]interface{}",
						Mandatory: false,
						Aliases:   []config.Alias{},
					},
					{
						Name: "helmChartUrl",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/helmChartUrl",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_helmChartUrl"),
					},
					{
						Name: "helmStagingRepositoryPassword",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/helmRepositoryPassword",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_helmStagingRepositoryPassword"),
					},
					{
						Name: "helmStagingRepositoryUsername",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/helmRepositoryUsername",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_helmStagingRepositoryUsername"),
					},
					{
						Name:        "targetPath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `./`,
					},
				},
			},
			Containers: []config.Container{
				{Image: "maven:3.6-jdk-8", Conditions: []config.Condition{{ConditionRef: "strings-equal", Params: []config.Param{{Name: "buildTool", Value: "maven"}}}}},
			},
			Outputs: config.StepOutputs{
				Resources: []config.StepResources{
					{
						Name: "commonPipelineEnvironment",
						Type: "piperEnvironment",
						Parameters: []map[string]interface{}{
							{"name": "custom/localHelmChartPath"},
							{"name": "custom/downloadTargetPath"},
						},
					},
				},
			},
		},
	}
	return theMetaData
}
