// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/spf13/cobra"
)

type sapExecuteFastlaneOptions struct {
	LaneName                           string `json:"laneName,omitempty"`
	Platform                           string `json:"platform,omitempty" validate:"possible-values=android ios mac"`
	SetupSigning                       bool   `json:"setupSigning,omitempty"`
	SetupBundlerAuthentication         bool   `json:"setupBundlerAuthentication,omitempty"`
	Username                           string `json:"username,omitempty"`
	Password                           string `json:"password,omitempty"`
	FastlaneMatchPassphrase            string `json:"fastlaneMatchPassphrase,omitempty"`
	FastlaneMatchRepositoryCredentials string `json:"fastlaneMatchRepositoryCredentials,omitempty"`
}

// SapExecuteFastlaneCommand Execute fastlane lane
func SapExecuteFastlaneCommand() *cobra.Command {
	const STEP_NAME = "sapExecuteFastlane"

	metadata := sapExecuteFastlaneMetadata()
	var stepConfig sapExecuteFastlaneOptions
	var startTime time.Time
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapExecuteFastlaneCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "Execute fastlane lane",
		Long: `This step allows to execute a specific fastlane lane (defined in your ` + "`" + `Fastfile` + "`" + `) and ensures that the dependencies specified in your Gemfile.lock are installed.
It requires a Ruby installation (we recommend to use [RVM](https://rvm.io/rvm)). Also, it requires the Gemfile and/or Gemfile.lock and the fastlane folder to be present at the project root directory.
Please note that some fastlane actions require you to run on macOS.

You find details about fastlane here: [fastlane docs](https://docs.fastlane.tools/).`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.Username)
			log.RegisterSecret(stepConfig.Password)
			log.RegisterSecret(stepConfig.FastlaneMatchPassphrase)
			log.RegisterSecret(stepConfig.FastlaneMatchRepositoryCredentials)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapExecuteFastlane(stepConfig, &stepTelemetryData)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapExecuteFastlaneFlags(createSapExecuteFastlaneCmd, &stepConfig)
	return createSapExecuteFastlaneCmd
}

func addSapExecuteFastlaneFlags(cmd *cobra.Command, stepConfig *sapExecuteFastlaneOptions) {
	cmd.Flags().StringVar(&stepConfig.LaneName, "laneName", os.Getenv("PIPER_laneName"), "Name of the lane in your Fastfile that shall be executed using bundle exec fastlane <laneName>.")
	cmd.Flags().StringVar(&stepConfig.Platform, "platform", `ios`, "Platform name where the lane is specified in your `Fastfile`. This will mainly impact whether this step tries to set up `fastlane match` (iOS-only) or not.")
	cmd.Flags().BoolVar(&stepConfig.SetupSigning, "setupSigning", false, "Whether Piper will inject iOS/macOS signing secrets for fastlane task")
	cmd.Flags().BoolVar(&stepConfig.SetupBundlerAuthentication, "setupBundlerAuthentication", false, "Whether piper should run `bundle config` with username and password specified in `gitHttpsCredential`")
	cmd.Flags().StringVar(&stepConfig.Username, "username", os.Getenv("PIPER_username"), "User name for git authentication")
	cmd.Flags().StringVar(&stepConfig.Password, "password", os.Getenv("PIPER_password"), "Password/token for git authentication.")
	cmd.Flags().StringVar(&stepConfig.FastlaneMatchPassphrase, "fastlaneMatchPassphrase", os.Getenv("PIPER_fastlaneMatchPassphrase"), "(iOS/macOS only) AES-256-cbc key (passphrase) used for `fastlane match`.")
	cmd.Flags().StringVar(&stepConfig.FastlaneMatchRepositoryCredentials, "fastlaneMatchRepositoryCredentials", os.Getenv("PIPER_fastlaneMatchRepositoryCredentials"), "(iOS/macOS only) Basic authentication token used to access the fastlane match git storage.")

	cmd.MarkFlagRequired("laneName")
}

// retrieve step metadata
func sapExecuteFastlaneMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapExecuteFastlane",
			Aliases:     []config.Alias{},
			Description: "Execute fastlane lane",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "gitHttpsCredentialsId", Description: "Jenkins 'Username with password' credentials ID containing username/password for http access to github.tools.sap", Type: "jenkins"},
				},
				Parameters: []config.StepParameters{
					{
						Name:        "laneName",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_laneName"),
					},
					{
						Name:        "platform",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `ios`,
					},
					{
						Name:        "setupSigning",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "setupBundlerAuthentication",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name: "username",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "gitHttpsCredentialsId",
								Param: "username",
								Type:  "secret",
							},

							{
								Name:    "gitHttpsCredentialsVaultSecretName",
								Type:    "vaultSecret",
								Default: "gitHttpsCredential",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_username"),
					},
					{
						Name: "password",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "gitHttpsCredentialsId",
								Param: "password",
								Type:  "secret",
							},

							{
								Name:    "gitHttpsCredentialsVaultSecretName",
								Type:    "vaultSecret",
								Default: "gitHttpsCredential",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_password"),
					},
					{
						Name: "fastlaneMatchPassphrase",
						ResourceRef: []config.ResourceReference{
							{
								Name:    "fastlaneMatchPassphraseVaultSecretName",
								Type:    "vaultSecret",
								Default: "fastlane",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_fastlaneMatchPassphrase"),
					},
					{
						Name: "fastlaneMatchRepositoryCredentials",
						ResourceRef: []config.ResourceReference{
							{
								Name:    "fastlaneMatchRepositoryCredentialsVaultSecretName",
								Type:    "vaultSecret",
								Default: "fastlane",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_fastlaneMatchRepositoryCredentials"),
					},
				},
			},
		},
	}
	return theMetaData
}
