// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/spf13/cobra"
)

type sapExecuteCentralPolicyOptions struct {
	JSONKeyFilePath           string `json:"jsonKeyFilePath,omitempty"`
	Token                     string `json:"token,omitempty"`
	PolicyKey                 string `json:"policyKey,omitempty"`
	EvidenceFile              string `json:"evidenceFile,omitempty"`
	CentralPolicyPath         string `json:"centralPolicyPath,omitempty"`
	FailOnPolicyViolation     bool   `json:"failOnPolicyViolation,omitempty"`
	ResultFile                string `json:"resultFile,omitempty"`
	GenerateJunitReport       bool   `json:"generateJunitReport,omitempty"`
	GithubToken               string `json:"githubToken,omitempty"`
	CumulusPolicyAgentVersion string `json:"cumulusPolicyAgentVersion,omitempty"`
	CumulusPolicyBucket       string `json:"cumulusPolicyBucket,omitempty"`
}

// SapExecuteCentralPolicyCommand Execute a central policy.
func SapExecuteCentralPolicyCommand() *cobra.Command {
	const STEP_NAME = "sapExecuteCentralPolicy"

	metadata := sapExecuteCentralPolicyMetadata()
	var stepConfig sapExecuteCentralPolicyOptions
	var startTime time.Time
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapExecuteCentralPolicyCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "Execute a central policy.",
		Long: `This step evaluates central policies which you can use to validate the quality of your software.

For the evaluation, you need to provide an evidence file which contains the measured properties of your software and the key oft the central policy to execute.
This step validates the evidence file against the central policy and stores the result in a json file.

The central policies will be downloaded automatically from cumulus.
By default policy violations will abort the pipeline (can be changed by ` + "`" + `failOnPolicyViolation` + "`" + ` parameter to ` + "`" + `false` + "`" + `).

Example:
In order to execute a central policy you have to call the step sapExecuteCentralPolicy i.e. by using a piper extension.

` + "`" + `` + "`" + `` + "`" + `
sapExecuteCentralPolicy script: script, policyKey: 'SDOL-009', evidenceFile: 'my-evidence-1.json'
` + "`" + `` + "`" + `` + "`" + `

A working showcase with [piper extension](https://github.wdf.sap.corp/cumulus/cumulus-showcase-nestjs/blob/master/.pipeline/extensions/Central%20Build.groovy) and a policy can be found in the [cumulus-showcase-nestjs](https://github.wdf.sap.corp/cumulus/cumulus-showcase-nestjs/tree/master/.policy/code_coverage) repository.

Cumulus Integration:

The generated result file can be uploaded to [Cumulus](https://go.sap.corp/piper/steps/sapCumulusUpload/):
` + "`" + `` + "`" + `` + "`" + `
sapCumulusUpload script: this, filePattern: 'policy-result/SDOL-009/**/*.json', subFolderPath: 'SDOL-009', stepResultType: 'policy-result'
` + "`" + `` + "`" + `` + "`" + `
This can be used for documentation purposes and to display the results in the [Cumulus pipeline dashboard](https://wiki.one.int.sap/wiki/x/icIy1g#PoliciesasCode-WherecanIseepolicyresults?).`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.JSONKeyFilePath)
			log.RegisterSecret(stepConfig.Token)
			log.RegisterSecret(stepConfig.GithubToken)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapExecuteCentralPolicy(stepConfig, &stepTelemetryData)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapExecuteCentralPolicyFlags(createSapExecuteCentralPolicyCmd, &stepConfig)
	return createSapExecuteCentralPolicyCmd
}

func addSapExecuteCentralPolicyFlags(cmd *cobra.Command, stepConfig *sapExecuteCentralPolicyOptions) {
	cmd.Flags().StringVar(&stepConfig.JSONKeyFilePath, "jsonKeyFilePath", os.Getenv("PIPER_jsonKeyFilePath"), "File path to Google Cloud JSON key file. If this parameter is not set, the 'token' parameter will be used for authentication.")
	cmd.Flags().StringVar(&stepConfig.Token, "token", os.Getenv("PIPER_token"), "The token used to authenticate with the Google Cloud Storage service. It is provided by TrustEngine, so usually there is no need to set this parameter.")
	cmd.Flags().StringVar(&stepConfig.PolicyKey, "policyKey", os.Getenv("PIPER_policyKey"), "The key of the policy to be executed.")
	cmd.Flags().StringVar(&stepConfig.EvidenceFile, "evidenceFile", os.Getenv("PIPER_evidenceFile"), "The evidence file to be evaluated.")
	cmd.Flags().StringVar(&stepConfig.CentralPolicyPath, "centralPolicyPath", `.central-policy-cache`, "Path of a directory containing the policies.")
	cmd.Flags().BoolVar(&stepConfig.FailOnPolicyViolation, "failOnPolicyViolation", true, "Fail the pipeline if the policy is not compliant.")
	cmd.Flags().StringVar(&stepConfig.ResultFile, "resultFile", `./policy-result/<policyKey>/result.json`, "Path of the result file that is generated. The placeholder <policyKey> will be replaced by the policy key.\nThe path can contain subfolders which might be useful if the same policy is executed multiple times (e.g. mono repo / maven multi module project)\nAttention: If you execute the same policy multiple times without specifying resultFile parameter results will be overwritten.\n")
	cmd.Flags().BoolVar(&stepConfig.GenerateJunitReport, "generateJunitReport", false, "Whether a junit test-report xml is generated or not. If so, the report will be generated at the following path: ./TEST-central-policy-<policyKey>.xml\n")
	cmd.Flags().StringVar(&stepConfig.GithubToken, "githubToken", os.Getenv("PIPER_githubToken"), "Token of Git user for GitHub access. Required if pipeline is running outside of the corporate network.")
	cmd.Flags().StringVar(&stepConfig.CumulusPolicyAgentVersion, "cumulusPolicyAgentVersion", `latest`, "The version of the cumulus policy agent to be used for the execution.\nNote: Normally you should use the default\n")
	cmd.Flags().StringVar(&stepConfig.CumulusPolicyBucket, "cumulusPolicyBucket", `sap-cumulus-store-prod-policy-bundles`, "The bucket containing the central policy bundles\nNote: Normally you should use the default\n")

	cmd.MarkFlagRequired("policyKey")
	cmd.MarkFlagRequired("evidenceFile")
}

// retrieve step metadata
func sapExecuteCentralPolicyMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapExecuteCentralPolicy",
			Aliases:     []config.Alias{},
			Description: "Execute a central policy.",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "githubTokenCredentialsId", Description: "Jenkins 'Secret text' credentials ID containing the token used to authenticate with the Github server.", Type: "jenkins"},
					{Name: "cumulusFileCredentialsId", Description: "Jenkins 'File' credentials ID containing the key file to authenticate to Cumulus on the Google Cloud Platform.", Type: "jenkins"},
				},
				Parameters: []config.StepParameters{
					{
						Name: "jsonKeyFilePath",
						ResourceRef: []config.ResourceReference{
							{
								Name: "cumulusFileCredentialsId",
								Type: "secret",
							},

							{
								Name:    "cumulusFileCredentialsVaultSecretName",
								Type:    "vaultSecretFile",
								Default: "cumulus",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_jsonKeyFilePath"),
					},
					{
						Name: "token",
						ResourceRef: []config.ResourceReference{
							{
								Name:    "cumulusSystemTrustSecretName",
								Type:    "systemTrustSecret",
								Default: "cumulus",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_token"),
					},
					{
						Name:        "policyKey",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_policyKey"),
					},
					{
						Name:        "evidenceFile",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_evidenceFile"),
					},
					{
						Name:        "centralPolicyPath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS", "GENERAL"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `.central-policy-cache`,
					},
					{
						Name:        "failOnPolicyViolation",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS", "GENERAL"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     true,
					},
					{
						Name:        "resultFile",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `./policy-result/<policyKey>/result.json`,
					},
					{
						Name:        "generateJunitReport",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name: "githubToken",
						ResourceRef: []config.ResourceReference{
							{
								Name: "githubTokenCredentialsId",
								Type: "secret",
							},

							{
								Name:    "githubTokenCredentialsVaultSecretName",
								Type:    "vaultSecret",
								Default: "github",
							},
						},
						Scope:     []string{"PARAMETERS", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{{Name: "access_token"}},
						Default:   os.Getenv("PIPER_githubToken"),
					},
					{
						Name:        "cumulusPolicyAgentVersion",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS", "GENERAL"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `latest`,
					},
					{
						Name:        "cumulusPolicyBucket",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS", "GENERAL"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `sap-cumulus-store-prod-policy-bundles`,
					},
				},
			},
		},
	}
	return theMetaData
}
