// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/piperenv"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/spf13/cobra"
)

type sapGithubWriteDeploymentOptions struct {
	Status           string `json:"status,omitempty"`
	CreateNew        bool   `json:"createNew,omitempty"`
	Environment      string `json:"environment,omitempty"`
	APIURL           string `json:"apiUrl,omitempty"`
	IsProduction     bool   `json:"isProduction,omitempty"`
	DeploymentID     string `json:"deploymentID,omitempty"`
	GithubAPITimeout int    `json:"githubApiTimeout,omitempty"`
	Comitish         string `json:"comitish,omitempty"`
	Owner            string `json:"owner,omitempty"`
	Repository       string `json:"repository,omitempty"`
	Token            string `json:"token,omitempty"`
}

type sapGithubWriteDeploymentCommonPipelineEnvironment struct {
	git struct {
		github_deploymentID string
	}
}

func (p *sapGithubWriteDeploymentCommonPipelineEnvironment) persist(path, resourceName string) {
	content := []struct {
		category string
		name     string
		value    interface{}
	}{
		{category: "git", name: "github_deploymentId", value: p.git.github_deploymentID},
	}

	errCount := 0
	for _, param := range content {
		err := piperenv.SetResourceParameter(path, resourceName, filepath.Join(param.category, param.name), param.value)
		if err != nil {
			log.Entry().WithError(err).Error("Error persisting piper environment.")
			errCount++
		}
	}
	if errCount > 0 {
		log.Entry().Error("failed to persist Piper environment")
	}
}

// SapGithubWriteDeploymentCommand Create or update GitHub deployment status
func SapGithubWriteDeploymentCommand() *cobra.Command {
	const STEP_NAME = "sapGithubWriteDeployment"

	metadata := sapGithubWriteDeploymentMetadata()
	var stepConfig sapGithubWriteDeploymentOptions
	var startTime time.Time
	var commonPipelineEnvironment sapGithubWriteDeploymentCommonPipelineEnvironment
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapGithubWriteDeploymentCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "Create or update GitHub deployment status",
		Long: `Create a new deployment in GitHub or update the status of an existing deployment.

This step supports three modes:

1. **Create a new deployment**
   Set ` + "`" + `createNew: true` + "`" + ` to create a new deployment. The newly created deployment ID
   will be stored in the pipeline environment at ` + "`" + `git/github_deploymentId` + "`" + ` for use in later steps.

2. **Create a new deployment and set its initial status**
   Set ` + "`" + `createNew: true` + "`" + ` and provide a ` + "`" + `status` + "`" + ` value. This will create the deployment and
   immediately set a deployment status to track the deployment progress.

3. **Update the status of an existing deployment**
   Provide an existing ` + "`" + `deploymentID` + "`" + ` (for example from ` + "`" + `git/github_deploymentId` + "`" + `) along with a ` + "`" + `status` + "`" + `.
   This mode does not create a new deployment; it only creates a new deployment status entry.

**Deployment Status Values:**

The most commonly used deployment statuses are:
- ` + "`" + `in_progress` + "`" + ` - Indicates the deployment is currently running
- ` + "`" + `success` + "`" + ` - Indicates the deployment completed successfully
- ` + "`" + `failure` + "`" + ` - Indicates the deployment failed

Additional valid status values include:
- ` + "`" + `pending` + "`" + ` - Deployment is waiting to start
- ` + "`" + `queued` + "`" + ` - Deployment is queued for execution
- ` + "`" + `error` + "`" + ` - An error occurred during deployment
- ` + "`" + `inactive` + "`" + ` - Deployment is inactive (appears as "destroyed" in GitHub UI)

Choose the appropriate status based on your deployment lifecycle. Use ` + "`" + `in_progress` + "`" + ` when starting a deployment,
` + "`" + `success` + "`" + ` when the deployment completes successfully, and ` + "`" + `failure` + "`" + ` when issues occur.

All modes require a valid GitHub token with permissions to create deployments and statuses in the target repository.

For more details on GitHub deployments, see the
[GitHub REST API documentation](https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28#about-deployments).`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.Token)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				commonPipelineEnvironment.persist(piperOsCmd.GeneralConfig.EnvRootPath, "commonPipelineEnvironment")
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapGithubWriteDeployment(stepConfig, &stepTelemetryData, &commonPipelineEnvironment)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapGithubWriteDeploymentFlags(createSapGithubWriteDeploymentCmd, &stepConfig)
	return createSapGithubWriteDeploymentCmd
}

func addSapGithubWriteDeploymentFlags(cmd *cobra.Command, stepConfig *sapGithubWriteDeploymentOptions) {
	cmd.Flags().StringVar(&stepConfig.Status, "status", os.Getenv("PIPER_status"), "Deployment status to set. Common values: 'in_progress' (deployment running), 'success' (deployment completed), 'failure' (deployment failed). Additional valid values: 'pending', 'queued', 'error', 'inactive'.")
	cmd.Flags().BoolVar(&stepConfig.CreateNew, "createNew", false, "If 'true', creates a new deployment instead of updating the status of an existing one")
	cmd.Flags().StringVar(&stepConfig.Environment, "environment", os.Getenv("PIPER_environment"), "Environment name for the deployment (e.g., 'production', 'staging', 'development'). See GitHub API documentation for details.")
	cmd.Flags().StringVar(&stepConfig.APIURL, "apiUrl", `https://github.tools.sap/api/v3`, "GitHub API URL. Use `https://github.tools.sap/api/v3` for GitHub Enterprise or `https://api.github.com` for public GitHub. Specify the appropriate URL based on your repository location.")
	cmd.Flags().BoolVar(&stepConfig.IsProduction, "isProduction", false, "Indicates whether this is a production environment deployment. This affects how GitHub displays the deployment.")
	cmd.Flags().StringVar(&stepConfig.DeploymentID, "deploymentID", os.Getenv("PIPER_deploymentID"), "Deployment ID for updating the status of an existing deployment. Automatically retrieved from pipeline environment if available.")
	cmd.Flags().IntVar(&stepConfig.GithubAPITimeout, "githubApiTimeout", 30, "HTTP timeout for GitHub API calls in seconds")
	cmd.Flags().StringVar(&stepConfig.Comitish, "comitish", `master`, "Target git commit, branch, or tag for the deployment")
	cmd.Flags().StringVar(&stepConfig.Owner, "owner", os.Getenv("PIPER_owner"), "GitHub organization or user name that owns the repository")
	cmd.Flags().StringVar(&stepConfig.Repository, "repository", os.Getenv("PIPER_repository"), "GitHub repository name")
	cmd.Flags().StringVar(&stepConfig.Token, "token", os.Getenv("PIPER_token"), "GitHub personal access token with 'repo_deployment' scope (recommended) or 'repo' scope for deployment management. For fine-grained tokens, requires 'Deployments' repository permissions (write).")

	cmd.MarkFlagRequired("apiUrl")
	cmd.MarkFlagRequired("owner")
	cmd.MarkFlagRequired("repository")
	cmd.MarkFlagRequired("token")
}

// retrieve step metadata
func sapGithubWriteDeploymentMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapGithubWriteDeployment",
			Aliases:     []config.Alias{},
			Description: "Create or update GitHub deployment status",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "githubTokenCredentialsId", Description: "Jenkins 'Secret text' credentials ID containing token to authenticate to GitHub.", Type: "jenkins"},
				},
				Parameters: []config.StepParameters{
					{
						Name:        "status",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_status"),
					},
					{
						Name:        "createNew",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "environment",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_environment"),
					},
					{
						Name:        "apiUrl",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{{Name: "githubApiUrl"}},
						Default:     `https://github.tools.sap/api/v3`,
					},
					{
						Name:        "isProduction",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name: "deploymentID",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/github_deploymentId",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_deploymentID"),
					},
					{
						Name:        "githubApiTimeout",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "int",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     30,
					},
					{
						Name: "comitish",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/headCommitId",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   `master`,
					},
					{
						Name: "owner",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/organization",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{{Name: "githubOrg"}},
						Default:   os.Getenv("PIPER_owner"),
					},
					{
						Name: "repository",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/repository",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{{Name: "githubRepo"}},
						Default:   os.Getenv("PIPER_repository"),
					},
					{
						Name: "token",
						ResourceRef: []config.ResourceReference{
							{
								Name: "githubTokenCredentialsId",
								Type: "secret",
							},

							{
								Name:    "githubVaultSecretName",
								Type:    "vaultSecret",
								Default: "github",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{{Name: "githubToken"}, {Name: "access_token"}},
						Default:   os.Getenv("PIPER_token"),
					},
				},
			},
			Outputs: config.StepOutputs{
				Resources: []config.StepResources{
					{
						Name: "commonPipelineEnvironment",
						Type: "piperEnvironment",
						Parameters: []map[string]interface{}{
							{"name": "git/github_deploymentId"},
						},
					},
				},
			},
		},
	}
	return theMetaData
}
