// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"reflect"
	"strings"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/gcs"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/bmatcuk/doublestar"
	"github.com/spf13/cobra"
)

type sapGenerateEnvironmentInfoOptions struct {
	OutputPath              string   `json:"outputPath,omitempty"`
	OutputBuildSettingsPath string   `json:"outputBuildSettingsPath,omitempty"`
	OutputPiperConfigPath   string   `json:"outputPiperConfigPath,omitempty"`
	Scheduled               bool     `json:"scheduled,omitempty"`
	BuildEnvironment        string   `json:"buildEnvironment,omitempty"`
	BuildTool               string   `json:"buildTool,omitempty"`
	BuildSettingsInfo       string   `json:"buildSettingsInfo,omitempty"`
	ReleaseStatus           string   `json:"releaseStatus,omitempty"`
	GenerateFiles           []string `json:"generateFiles,omitempty" validate:"possible-values=envInfo buildSettings piperConfig releaseStatus"`
	GitBranch               string   `json:"gitBranch,omitempty"`
	GitCommitID             string   `json:"gitCommitId,omitempty"`
	GitHeadCommitID         string   `json:"gitHeadCommitId,omitempty"`
	GitHttpsURL             string   `json:"gitHttpsUrl,omitempty"`
	PipelineOptimization    bool     `json:"pipelineOptimization,omitempty"`
	UseCommitIDForCumulus   bool     `json:"useCommitIdForCumulus,omitempty"`
	PiperConfig             string   `json:"piperConfig,omitempty"`
}

type sapGenerateEnvironmentInfoReports struct {
}

func (p *sapGenerateEnvironmentInfoReports) persist(stepConfig sapGenerateEnvironmentInfoOptions, gcpJsonKeyFilePath string, gcsBucketId string, gcsFolderPath string, gcsSubFolder string) {
	if gcsBucketId == "" {
		log.Entry().Info("persisting reports to GCS is disabled, because gcsBucketId is empty")
		return
	}
	log.Entry().Info("Uploading reports to Google Cloud Storage...")
	content := []gcs.ReportOutputParam{
		{FilePattern: "env*.json", ParamRef: "", StepResultType: "root"},
		{FilePattern: "build-settings.json", ParamRef: "", StepResultType: "settings"},
		{FilePattern: "release-status-*.json", ParamRef: "", StepResultType: ".status-log/release"},
	}

	gcsClient, err := gcs.NewClient(gcpJsonKeyFilePath, "")
	if err != nil {
		log.Entry().Errorf("creation of GCS client failed: %v", err)
		return
	}
	defer gcsClient.Close()
	structVal := reflect.ValueOf(&stepConfig).Elem()
	inputParameters := map[string]string{}
	for i := 0; i < structVal.NumField(); i++ {
		field := structVal.Type().Field(i)
		if field.Type.String() == "string" {
			paramName := strings.Split(field.Tag.Get("json"), ",")
			paramValue, _ := structVal.Field(i).Interface().(string)
			inputParameters[paramName[0]] = paramValue
		}
	}
	if err := gcs.PersistReportsToGCS(gcsClient, content, inputParameters, gcsFolderPath, gcsBucketId, gcsSubFolder, doublestar.Glob, os.Stat); err != nil {
		log.Entry().Errorf("failed to persist reports: %v", err)
	}
}

// SapGenerateEnvironmentInfoCommand
func SapGenerateEnvironmentInfoCommand() *cobra.Command {
	const STEP_NAME = "sapGenerateEnvironmentInfo"

	metadata := sapGenerateEnvironmentInfoMetadata()
	var stepConfig sapGenerateEnvironmentInfoOptions
	var startTime time.Time
	var reports sapGenerateEnvironmentInfoReports
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapGenerateEnvironmentInfoCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "",
		Long: `Generates a JSON file which can be uploaded to Cumulus using ` + "`" + `sapCumulusUpload` + "`" + `.  The content of that file is automatically detected from the CI environment.
It currently supports: Azure DevOps (Pipelines), GitHub Actions, Jenkins.
The JSON file has the following format:
` + "`" + `` + "`" + `` + "`" + `json
{
  "BUILD_URL": "<link to the build job that triggered the upload>",
  "GIT_BRANCH": "<branch or tag name>",
  "GIT_COMMIT": "<commit id that triggers the pipeline>",
  "GIT_TAG_COMMIT": "<commit id generated after artifactPrepareVersion writes github tag when after versioningType is cloud>",
  "GIT_URL": "<repository url (used for determining SLC-25 compliance>",
  "PIPELINE_RUN_MODE":"<different pipeline run modes useful for Cumulus>",
  "isScheduled":"<set to true for scheduled pipeline>"
}
` + "`" + `` + "`" + `` + "`" + ``,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				reports.persist(stepConfig, piperOsCmd.GeneralConfig.GCPJsonKeyFilePath, piperOsCmd.GeneralConfig.GCSBucketId, piperOsCmd.GeneralConfig.GCSFolderPath, piperOsCmd.GeneralConfig.GCSSubFolder)
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapGenerateEnvironmentInfo(stepConfig, &stepTelemetryData)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapGenerateEnvironmentInfoFlags(createSapGenerateEnvironmentInfoCmd, &stepConfig)
	return createSapGenerateEnvironmentInfoCmd
}

func addSapGenerateEnvironmentInfoFlags(cmd *cobra.Command, stepConfig *sapGenerateEnvironmentInfoOptions) {
	cmd.Flags().StringVar(&stepConfig.OutputPath, "outputPath", `./env.json`, "Specifies where the environment information shall be written to.")
	cmd.Flags().StringVar(&stepConfig.OutputBuildSettingsPath, "outputBuildSettingsPath", `./build-settings.json`, "Specifies where the environment information shall be written to.")
	cmd.Flags().StringVar(&stepConfig.OutputPiperConfigPath, "outputPiperConfigPath", `./piper-config.yaml`, "Specifies where the piper config information shall be written to.")
	cmd.Flags().BoolVar(&stepConfig.Scheduled, "scheduled", false, "Flag if the build was triggered by schedule.")
	cmd.Flags().StringVar(&stepConfig.BuildEnvironment, "buildEnvironment", os.Getenv("PIPER_buildEnvironment"), "Describes the used build environment.")
	cmd.Flags().StringVar(&stepConfig.BuildTool, "buildTool", os.Getenv("PIPER_buildTool"), "Defines the tool which is used for building the artifact.")
	cmd.Flags().StringVar(&stepConfig.BuildSettingsInfo, "buildSettingsInfo", os.Getenv("PIPER_buildSettingsInfo"), "Describes the buildSettings information was created during the build.")
	cmd.Flags().StringVar(&stepConfig.ReleaseStatus, "releaseStatus", os.Getenv("PIPER_releaseStatus"), "Describes the release status (e.g. promoted).")
	cmd.Flags().StringSliceVar(&stepConfig.GenerateFiles, "generateFiles", []string{`envInfo`, `buildSettings`, `piperConfig`}, "List of files to be generated")
	cmd.Flags().StringVar(&stepConfig.GitBranch, "gitBranch", os.Getenv("PIPER_gitBranch"), "Defines the git branch to be sent as part of the environment information.")
	cmd.Flags().StringVar(&stepConfig.GitCommitID, "gitCommitId", os.Getenv("PIPER_gitCommitId"), "Defines the commitId to be sent as part of the environment information.")
	cmd.Flags().StringVar(&stepConfig.GitHeadCommitID, "gitHeadCommitId", os.Getenv("PIPER_gitHeadCommitId"), "Specifies the headcommitId to be sent as part of the environment information.")
	cmd.Flags().StringVar(&stepConfig.GitHttpsURL, "gitHttpsUrl", os.Getenv("PIPER_gitHttpsUrl"), "Defines the gitHttpsUrl to be sent as part of the environment information.")
	cmd.Flags().BoolVar(&stepConfig.PipelineOptimization, "pipelineOptimization", false, "Describes the PIPELINE_RUN_MODE information.")
	cmd.Flags().BoolVar(&stepConfig.UseCommitIDForCumulus, "useCommitIdForCumulus", false, "Parameter in Beta mode. To be set to true if cumulus storage needs to be only with commit id.")
	cmd.Flags().StringVar(&stepConfig.PiperConfig, "piperConfig", os.Getenv("PIPER_piperConfig"), "Describes the piper config yaml used during the pipeline run.")

	cmd.MarkFlagRequired("buildTool")
}

// retrieve step metadata
func sapGenerateEnvironmentInfoMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapGenerateEnvironmentInfo",
			Aliases:     []config.Alias{},
			Description: "",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Parameters: []config.StepParameters{
					{
						Name:        "outputPath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `./env.json`,
					},
					{
						Name:        "outputBuildSettingsPath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `./build-settings.json`,
					},
					{
						Name:        "outputPiperConfigPath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `./piper-config.yaml`,
					},
					{
						Name: "scheduled",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/scheduledRun",
							},
						},
						Scope:     []string{"PARAMETERS", "STEPS"},
						Type:      "bool",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   false,
					},
					{
						Name: "buildEnvironment",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/buildEnv",
							},
						},
						Scope:     []string{"PARAMETERS", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_buildEnvironment"),
					},
					{
						Name:        "buildTool",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_buildTool"),
					},
					{
						Name: "buildSettingsInfo",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/buildSettingsInfo",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_buildSettingsInfo"),
					},
					{
						Name: "releaseStatus",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/releaseStatus",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_releaseStatus"),
					},
					{
						Name:        "generateFiles",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     []string{`envInfo`, `buildSettings`, `piperConfig`},
					},
					{
						Name: "gitBranch",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/branch",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitBranch"),
					},
					{
						Name: "gitCommitId",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/commitId",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitCommitId"),
					},
					{
						Name: "gitHeadCommitId",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/headCommitId",
							},
						},
						Scope:     []string{},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitHeadCommitId"),
					},
					{
						Name: "gitHttpsUrl",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/httpsUrl",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitHttpsUrl"),
					},
					{
						Name:        "pipelineOptimization",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "useCommitIdForCumulus",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name: "piperConfig",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/piperConfig",
							},
						},
						Scope:     []string{"GENERAL", "PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_piperConfig"),
					},
				},
			},
			Outputs: config.StepOutputs{
				Resources: []config.StepResources{
					{
						Name: "reports",
						Type: "reports",
						Parameters: []map[string]interface{}{
							{"filePattern": "env*.json", "type": "root"},
							{"filePattern": "build-settings.json", "type": "settings"},
							{"filePattern": "release-status-*.json", "type": ".status-log/release"},
						},
					},
				},
			},
		},
	}
	return theMetaData
}
