// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/piperenv"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/spf13/cobra"
)

type sapOcmCreateComponentOptions struct {
	DockerConfigJSON                 string   `json:"dockerConfigJSON,omitempty"`
	ComponentConstructorPath         string   `json:"componentConstructorPath,omitempty"`
	EnableOnPr                       bool     `json:"enableOnPr,omitempty"`
	Provider                         string   `json:"provider,omitempty"`
	ComponentName                    string   `json:"componentName,omitempty"`
	FailOnError                      bool     `json:"failOnError,omitempty"`
	GenDir                           string   `json:"genDir,omitempty"`
	ArtifactVersion                  string   `json:"artifactVersion,omitempty"`
	GitRepository                    string   `json:"gitRepository,omitempty"`
	GitCommitID                      string   `json:"gitCommitId,omitempty"`
	GitOrg                           string   `json:"gitOrg,omitempty"`
	GitURL                           string   `json:"gitURL,omitempty"`
	PromotedArtifactURLs             []string `json:"promotedArtifactURLs,omitempty"`
	ImageNames                       []string `json:"imageNames,omitempty"`
	ImageNameTags                    []string `json:"imageNameTags,omitempty"`
	ContainerRegistryURL             string   `json:"containerRegistryURL,omitempty"`
	ContainerRegistryUser            string   `json:"containerRegistryUser,omitempty"`
	ContainerRegistryPassword        string   `json:"containerRegistryPassword,omitempty"`
	HelmChartURL                     string   `json:"helmChartURL,omitempty"`
	HelmRepositoryUsername           string   `json:"helmRepositoryUsername,omitempty"`
	HelmRepositoryPassword           string   `json:"helmRepositoryPassword,omitempty"`
	StagingGroupID                   string   `json:"stagingGroupID,omitempty"`
	StagingServiceRepositoryUser     string   `json:"stagingServiceRepositoryUser,omitempty"`
	StagingServiceRepositoryPassword string   `json:"stagingServiceRepositoryPassword,omitempty"`
}

type sapOcmCreateComponentCommonPipelineEnvironment struct {
	custom struct {
		componentConstructor        string
		settingsYaml                string
		componentDescriptor         string
		ocmStagingRepo              string
		isCustomComponentDescriptor bool
	}
}

func (p *sapOcmCreateComponentCommonPipelineEnvironment) persist(path, resourceName string) {
	content := []struct {
		category string
		name     string
		value    interface{}
	}{
		{category: "custom", name: "componentConstructor", value: p.custom.componentConstructor},
		{category: "custom", name: "settingsYaml", value: p.custom.settingsYaml},
		{category: "custom", name: "componentDescriptor", value: p.custom.componentDescriptor},
		{category: "custom", name: "ocmStagingRepo", value: p.custom.ocmStagingRepo},
		{category: "custom", name: "isCustomComponentDescriptor", value: p.custom.isCustomComponentDescriptor},
	}

	errCount := 0
	for _, param := range content {
		err := piperenv.SetResourceParameter(path, resourceName, filepath.Join(param.category, param.name), param.value)
		if err != nil {
			log.Entry().WithError(err).Error("Error persisting piper environment.")
			errCount++
		}
	}
	if errCount > 0 {
		log.Entry().Error("failed to persist Piper environment")
	}
}

// SapOcmCreateComponentCommand Create an Open-Component-Model component-version
func SapOcmCreateComponentCommand() *cobra.Command {
	const STEP_NAME = "sapOcmCreateComponent"

	metadata := sapOcmCreateComponentMetadata()
	var stepConfig sapOcmCreateComponentOptions
	var startTime time.Time
	var commonPipelineEnvironment sapOcmCreateComponentCommonPipelineEnvironment
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapOcmCreateComponentCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "Create an Open-Component-Model component-version",
		Long: `This step creates a component-version of the Open-Component-Model (OCM).
For more information about OCM see <https://ocm.software>.
Currently only (multi-)container builds (incl. single helm-chart) are supported.

You can run this step either fully automated or in a customized way. In fully automated mode all information is taken from the pipeline configuration. The step generates a ` + "`" + `component-constructor.yaml` + "`" + ` file and calls [the OCM CLI](https://github.com/open-component-model/ocm/blob/main/docs/reference/ocm.md) to create the component-version. Some parameters (see below) can be set to control certain fields. In customized mode you provide your own ` + "`" + `component-constructor.yaml` + "`" + ` file in the source tree. The step detects if such a file exists and uses this instead of creating one. Default is ` + "`" + `component-constructor.yaml` + "`" + ` in the root directory. This file usually will be a template where certain variables will be replaced with values from the pipeline configuration. This step is by default disabled for pull requests, but can be enabled by configuration.

The following variables are available:

` + "`" + `` + "`" + `` + "`" + `
componentConstructorPath --> path to your custom component-constructor.yaml file
artifactVersion          --> version of this artifact
componentName            --> name of the component
containerRegistryURL     --> OCI registry of the build artifacts
containerRegistry        --> OCI registry - same as containerRegistryURL but without protocol
genDir                   --> path to directory where generated files are created
gitCommitId              --> commit hash in Git used for this build
gitOrg                   --> organization in Git
gitRepository            --> name of repository in Git
gitURL                   --> URL to Git repository
imageNames               --> array of image names (multi-image)
imageNameTags            --> array of name and tag (multi-image)
provider                 --> provider name of component version (default: SAP SE (gitOrg))
OCI_NAME_0               --> name of the OCI image (multi-image: 0, 1, ...)
OCI_REFERENCE_0          --> reference to the OCI image (multi-image: 0, 1, ...)
OCI_VERSION_0            --> version of the OCI image (multi-image: 0, 1, ...)
HELM_CHART               --> name of the helm chart if helm chart was build in a previous step
HELM_VERSION             --> version of helm chart if helm chart was build in a previous step
HELM_REPOSITORY          --> repository, where the helm chart is hosted
helmChartURL             --> URL to helm chart if helm chart was build in a previous step (helmExecute: true)
` + "`" + `` + "`" + `` + "`" + `

Here is an example:

` + "`" + `` + "`" + `` + "`" + `
componentConstructorPath: gen/component-constructor.yaml
artifactVersion: 0.0.1-dev-20240918153148+97feb5d34cebc31a8f9c56c8cd4fd8ff8003cd1e
componentName: open-component-model.sap.com/hello-ocm-helm
containerRegistryURL: https://f464b1e28081-20231025-131529839-554.staging.repositories.cloud.sap
containerRegistry: 371000438081-20240918-153224737-816.staging.repositories.cloud.sap
force: true
genDir: ./gen
gitCommitId: 97feb5d34cebc31a8f9c56c8cd4fd8ff8003cd1e
gitOrg: open-component-model
gitRepository: hello-ocm-helm
gitURL: https://github.tools.sap/open-component-model/hello-ocm-helm
imageNames:
  - hello-ocm-helm
imageNameTags:
  - hello-ocm-helm:0.0.1-dev-20240918153148_97feb5d34cebc31a8f9c56c8cd4fd8ff8003cd1e
provider: SAP SE (open-component-model)
OCI_NAME_0: hello-ocm-helm
OCI_REFERENCE_0: 371000108081-20240924-072300486-87.staging.repositories.cloud.sap/hello-ocm-helm:0.0.1-dev-20240924072222_7e63e6490e8a5d47ee14ca12500ad7aeea854b90
OCI_VERSION_0: 0.0.1-dev-20240924072222+7e63e6490e8a5d47ee14ca12500ad7aeea854b90
HELM_CHART: hello-ocm-helm
HELM_VERSION: 0.0.1-dev
HELM_REPOSITORY: https://staging.repositories.cloud.sap/stage/repository/371000698081-20240918-153224840-252
helmChartURL: https://staging.repositories.cloud.sap/stage/repository/371000698081-20240918-153224840-252/hello-ocm-helm-0.0.1-dev.tgz
` + "`" + `` + "`" + `` + "`" + `

An example ` + "`" + `component-constructor.yaml` + "`" + ` using some of these variables:

` + "`" + `` + "`" + `` + "`" + `
components:
- name: ${componentName}
  version: ${artifactVersion}
  provider:
    name: ${provider}
  sources:
  - name: src
    type: filesystem
    access:
      type: gitHub
      repoURL: ${gitURL}
      commit: ${gitCommitId}
  resources:
  - name: ${OCI_NAME_0}
    type: ociImage
    version: ${artifactVersion}
    access:
      type: ociArtifact
      imageReference: ${OCI_REFERENCE_0}
  - name: ${HELM_CHART}
      type: helmChart
      version: ${artifactVersion}
      access:
        type: helm
        helmChart: ${HELM_CHART}
        helmRepository: ${HELM_REPOSITORY}
        version: ${HELM_VERSION}
` + "`" + `` + "`" + `` + "`" + `

The created component-constructor + settings are stored as output from this step as yaml string.

So, ` + "`" + `sapOcmCreateComponent` + "`" + ` supports two major use cases:
1. Scenario: ` + "`" + `sapOcmCreateComponent` + "`" + ` runs as the last build step and generates OCM component descriptors for the artifacts built by the previous steps of the same pipeline run.
2. Scenario: ` + "`" + `sapOcmCreateComponent` + "`" + ` runs as the only tool and assembles OCM components and artifacts built elsewhere (not the current pipeline) to a bigger package.
The latter case can be configured as follows in the ` + "`" + `config.yml` + "`" + `:
` + "`" + `` + "`" + `` + "`" + `
general:
  buildTool: custom
  nativeBuild: true
  cnbBuild: false
stages:
  Build:
    sapOcmCreateComponent: true
steps:
  sapOcmCreateComponent:
    componentConstructorPath: some/path/my-ocm-component.yaml
  sapCallStagingService:
    buildTool: docker
` + "`" + `` + "`" + `` + "`" + `

Notes:

The version numbers generated by piper are not semver compatible. They are converted to a semver
compatible syntax.

[Starting point for developer documentation](https://github.wdf.sap.corp/ContinuousDelivery/piper-library/blob/main/pkg/sap/ocm/README.md)`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.DockerConfigJSON)
			log.RegisterSecret(stepConfig.ContainerRegistryUser)
			log.RegisterSecret(stepConfig.ContainerRegistryPassword)
			log.RegisterSecret(stepConfig.HelmRepositoryUsername)
			log.RegisterSecret(stepConfig.HelmRepositoryPassword)
			log.RegisterSecret(stepConfig.StagingServiceRepositoryPassword)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				commonPipelineEnvironment.persist(piperOsCmd.GeneralConfig.EnvRootPath, "commonPipelineEnvironment")
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapOcmCreateComponent(stepConfig, &stepTelemetryData, &commonPipelineEnvironment)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapOcmCreateComponentFlags(createSapOcmCreateComponentCmd, &stepConfig)
	return createSapOcmCreateComponentCmd
}

func addSapOcmCreateComponentFlags(cmd *cobra.Command, stepConfig *sapOcmCreateComponentOptions) {
	cmd.Flags().StringVar(&stepConfig.DockerConfigJSON, "dockerConfigJSON", os.Getenv("PIPER_dockerConfigJSON"), "Path to the file `.docker/config.json` - the file contains credentials required to access private OCI registries.")
	cmd.Flags().StringVar(&stepConfig.ComponentConstructorPath, "componentConstructorPath", os.Getenv("PIPER_componentConstructorPath"), "Path to component-constructor.yaml file")
	cmd.Flags().BoolVar(&stepConfig.EnableOnPr, "enableOnPr", false, "True if ocm step is enabled on pull-request builds")
	cmd.Flags().StringVar(&stepConfig.Provider, "provider", os.Getenv("PIPER_provider"), "The provider name to be used in the component descriptor")
	cmd.Flags().StringVar(&stepConfig.ComponentName, "componentName", os.Getenv("PIPER_componentName"), "The component name to be used in the component descriptor.\nIf not set, it's constructed by: [github_org].sap.com/[github_repo].\nIt has to match the regular expression: `^[a-z][-a-z0-9]*([.][a-z][-a-z0-9]*)*[.][a-z]{2,}(/[a-z][-a-z0-9_]*([.][a-z][-a-z0-9_]*)*)+$`\n")
	cmd.Flags().BoolVar(&stepConfig.FailOnError, "failOnError", true, "Indicates if the build should fail if component descriptor can not be generated")
	cmd.Flags().StringVar(&stepConfig.GenDir, "genDir", `gen`, "Path where generated files get written")
	cmd.Flags().StringVar(&stepConfig.ArtifactVersion, "artifactVersion", os.Getenv("PIPER_artifactVersion"), "The version assigned by artifactPrepareVersion to the uploaded artifact")
	cmd.Flags().StringVar(&stepConfig.GitRepository, "gitRepository", os.Getenv("PIPER_gitRepository"), "The name of the git repository")
	cmd.Flags().StringVar(&stepConfig.GitCommitID, "gitCommitId", os.Getenv("PIPER_gitCommitId"), "The commit id of the git repository")
	cmd.Flags().StringVar(&stepConfig.GitOrg, "gitOrg", os.Getenv("PIPER_gitOrg"), "The organization of the git repository")
	cmd.Flags().StringVar(&stepConfig.GitURL, "gitURL", os.Getenv("PIPER_gitURL"), "The URL of the git repository")
	cmd.Flags().StringSliceVar(&stepConfig.PromotedArtifactURLs, "promotedArtifactURLs", []string{}, "Promoted artifact urls")
	cmd.Flags().StringSliceVar(&stepConfig.ImageNames, "imageNames", []string{}, "List of image names")
	cmd.Flags().StringSliceVar(&stepConfig.ImageNameTags, "imageNameTags", []string{}, "List of image name tags")
	cmd.Flags().StringVar(&stepConfig.ContainerRegistryURL, "containerRegistryURL", os.Getenv("PIPER_containerRegistryURL"), "The URL of the container registry")
	cmd.Flags().StringVar(&stepConfig.ContainerRegistryUser, "containerRegistryUser", os.Getenv("PIPER_containerRegistryUser"), "The user of the container registry")
	cmd.Flags().StringVar(&stepConfig.ContainerRegistryPassword, "containerRegistryPassword", os.Getenv("PIPER_containerRegistryPassword"), "The password of the container registry")
	cmd.Flags().StringVar(&stepConfig.HelmChartURL, "helmChartURL", os.Getenv("PIPER_helmChartURL"), "The URL to the helm chart from a helmExecute output")
	cmd.Flags().StringVar(&stepConfig.HelmRepositoryUsername, "helmRepositoryUsername", os.Getenv("PIPER_helmRepositoryUsername"), "Username for the helm repository where the compiled helm .tgz archive shall be uploaded - typically provided by the CI/CD environment")
	cmd.Flags().StringVar(&stepConfig.HelmRepositoryPassword, "helmRepositoryPassword", os.Getenv("PIPER_helmRepositoryPassword"), "Password for the helm repository where the compiled helm .tgz archive shall be uploaded - typically provided by the CI/CD environment")
	cmd.Flags().StringVar(&stepConfig.StagingGroupID, "stagingGroupID", os.Getenv("PIPER_stagingGroupID"), "Defines the id of the staging service group")
	cmd.Flags().StringVar(&stepConfig.StagingServiceRepositoryUser, "stagingServiceRepositoryUser", os.Getenv("PIPER_stagingServiceRepositoryUser"), "Username for the repository created from staging services")
	cmd.Flags().StringVar(&stepConfig.StagingServiceRepositoryPassword, "stagingServiceRepositoryPassword", os.Getenv("PIPER_stagingServiceRepositoryPassword"), "Password for the repository created from staging services")

}

// retrieve step metadata
func sapOcmCreateComponentMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapOcmCreateComponent",
			Aliases:     []config.Alias{},
			Description: "Create an Open-Component-Model component-version",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "dockerConfigJsonCredentialsId", Description: "Secret file credentials ID containing Docker config.json. The file will be passed to OCM toolkit, to connect to private OCI registries.", Type: "jenkins"},
				},
				Parameters: []config.StepParameters{
					{
						Name: "dockerConfigJSON",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/dockerConfigJSON",
							},

							{
								Name: "dockerConfigJsonCredentialsId",
								Type: "secret",
							},

							{
								Name:    "dockerConfigFileVaultSecretName",
								Type:    "vaultSecretFile",
								Default: "docker-config",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_dockerConfigJSON"),
					},
					{
						Name:        "componentConstructorPath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_componentConstructorPath"),
					},
					{
						Name:        "enableOnPr",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "provider",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_provider"),
					},
					{
						Name:        "componentName",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_componentName"),
					},
					{
						Name:        "failOnError",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     true,
					},
					{
						Name:        "genDir",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `gen`,
					},
					{
						Name: "artifactVersion",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "artifactVersion",
							},
						},
						Scope:     []string{"PARAMETERS", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_artifactVersion"),
					},
					{
						Name: "gitRepository",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/repository",
							},
						},
						Scope:     []string{},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitRepository"),
					},
					{
						Name: "gitCommitId",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/commitId",
							},
						},
						Scope:     []string{},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitCommitId"),
					},
					{
						Name: "gitOrg",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/organization",
							},
						},
						Scope:     []string{},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitOrg"),
					},
					{
						Name: "gitURL",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/url",
							},
						},
						Scope:     []string{},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitURL"),
					},
					{
						Name: "promotedArtifactURLs",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/promotedArtifactUrls",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "[]string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   []string{},
					},
					{
						Name: "imageNames",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "container/imageNames",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "[]string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   []string{},
					},
					{
						Name: "imageNameTags",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "container/imageNameTags",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "[]string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   []string{},
					},
					{
						Name: "containerRegistryURL",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "container/registryUrl",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_containerRegistryURL"),
					},
					{
						Name: "containerRegistryUser",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "container/repositoryUsername",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_containerRegistryUser"),
					},
					{
						Name: "containerRegistryPassword",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "container/repositoryPassword",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_containerRegistryPassword"),
					},
					{
						Name: "helmChartURL",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/helmChartUrl",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_helmChartURL"),
					},
					{
						Name: "helmRepositoryUsername",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/helmRepositoryUsername",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_helmRepositoryUsername"),
					},
					{
						Name: "helmRepositoryPassword",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/helmRepositoryPassword",
							},

							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/repositoryPassword",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_helmRepositoryPassword"),
					},
					{
						Name: "stagingGroupID",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/stagingGroupId",
							},
						},
						Scope:     []string{},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_stagingGroupID"),
					},
					{
						Name: "stagingServiceRepositoryUser",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/repositoryUsername",
							},
						},
						Scope:     []string{},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_stagingServiceRepositoryUser"),
					},
					{
						Name: "stagingServiceRepositoryPassword",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/repositoryPassword",
							},
						},
						Scope:     []string{},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_stagingServiceRepositoryPassword"),
					},
				},
			},
			Containers: []config.Container{
				{Image: "ghcr.io/open-component-model/piper-ocm-cli:0.31.0"},
			},
			Outputs: config.StepOutputs{
				Resources: []config.StepResources{
					{
						Name: "ocm",
						Type: "generated",
						Parameters: []map[string]interface{}{
							{"filePattern": "**/component-constructor.yaml", "type": "ocm"},
							{"filePattern": "**/settings.yaml", "type": "ocm"},
						},
					},
					{
						Name: "commonPipelineEnvironment",
						Type: "piperEnvironment",
						Parameters: []map[string]interface{}{
							{"name": "custom/componentConstructor"},
							{"name": "custom/settingsYaml"},
							{"name": "custom/componentDescriptor"},
							{"name": "custom/ocmStagingRepo"},
							{"name": "custom/isCustomComponentDescriptor", "type": "bool"},
						},
					},
				},
			},
		},
	}
	return theMetaData
}
