// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/piperenv"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/spf13/cobra"
)

type sapPipelineInitOptions struct {
	PipelineOptimization  bool   `json:"pipelineOptimization,omitempty"`
	BuildURL              string `json:"buildURL,omitempty"`
	ProductiveBranch      string `json:"productiveBranch,omitempty"`
	IsScheduled           bool   `json:"isScheduled,omitempty"`
	GithubAPIURL          string `json:"githubApiUrl,omitempty"`
	PipelineID            string `json:"pipelineId,omitempty"`
	GithubToken           string `json:"githubToken,omitempty"`
	UseCommitIDForCumulus bool   `json:"useCommitIdForCumulus,omitempty"`
}

type sapPipelineInitCommonPipelineEnvironment struct {
	custom struct {
		isOptimizedAndScheduled bool
		scheduledRun            bool
		cumulusPipelineID       string
		gcsBucketID             string
		isProductiveBranch      bool
		piperConfig             string
		eventData               string
	}
	git struct {
		instance            string
		repository          string
		organization        string
		branch              string
		commitID            string
		headCommitID        string
		url                 string
		github_changes      int
		github_additions    int
		github_deletions    int
		github_filesChanged int
	}
}

func (p *sapPipelineInitCommonPipelineEnvironment) persist(path, resourceName string) {
	content := []struct {
		category string
		name     string
		value    interface{}
	}{
		{category: "custom", name: "isOptimizedAndScheduled", value: p.custom.isOptimizedAndScheduled},
		{category: "custom", name: "scheduledRun", value: p.custom.scheduledRun},
		{category: "custom", name: "cumulusPipelineID", value: p.custom.cumulusPipelineID},
		{category: "custom", name: "gcsBucketID", value: p.custom.gcsBucketID},
		{category: "custom", name: "isProductiveBranch", value: p.custom.isProductiveBranch},
		{category: "custom", name: "piperConfig", value: p.custom.piperConfig},
		{category: "git", name: "instance", value: p.git.instance},
		{category: "git", name: "repository", value: p.git.repository},
		{category: "git", name: "organization", value: p.git.organization},
		{category: "git", name: "branch", value: p.git.branch},
		{category: "git", name: "commitId", value: p.git.commitID},
		{category: "git", name: "headCommitId", value: p.git.headCommitID},
		{category: "git", name: "url", value: p.git.url},
		{category: "git", name: "github_changes", value: p.git.github_changes},
		{category: "git", name: "github_additions", value: p.git.github_additions},
		{category: "git", name: "github_deletions", value: p.git.github_deletions},
		{category: "git", name: "github_filesChanged", value: p.git.github_filesChanged},
		{category: "custom", name: "eventData", value: p.custom.eventData},
	}

	errCount := 0
	for _, param := range content {
		err := piperenv.SetResourceParameter(path, resourceName, filepath.Join(param.category, param.name), param.value)
		if err != nil {
			log.Entry().WithError(err).Error("Error persisting piper environment.")
			errCount++
		}
	}
	if errCount > 0 {
		log.Entry().Error("failed to persist Piper environment")
	}
}

type sapPipelineInitInflux struct {
	step_data struct {
		fields struct {
			build_url string
		}
		tags struct {
		}
	}
	pipeline_data struct {
		fields struct {
			build_url           string
			github_changes      int
			github_additions    int
			github_deletions    int
			github_filesChanged int
			cumulusPipelineID   string
			gcsBucketID         string
		}
		tags struct {
		}
	}
	jenkins_custom_data struct {
		fields struct {
			build_result     string
			build_result_key int
		}
		tags struct {
		}
	}
}

func (i *sapPipelineInitInflux) persist(path, resourceName string) {
	measurementContent := []struct {
		measurement string
		valType     string
		name        string
		value       interface{}
	}{
		{valType: config.InfluxField, measurement: "step_data", name: "build_url", value: i.step_data.fields.build_url},
		{valType: config.InfluxField, measurement: "pipeline_data", name: "build_url", value: i.pipeline_data.fields.build_url},
		{valType: config.InfluxField, measurement: "pipeline_data", name: "github_changes", value: i.pipeline_data.fields.github_changes},
		{valType: config.InfluxField, measurement: "pipeline_data", name: "github_additions", value: i.pipeline_data.fields.github_additions},
		{valType: config.InfluxField, measurement: "pipeline_data", name: "github_deletions", value: i.pipeline_data.fields.github_deletions},
		{valType: config.InfluxField, measurement: "pipeline_data", name: "github_filesChanged", value: i.pipeline_data.fields.github_filesChanged},
		{valType: config.InfluxField, measurement: "pipeline_data", name: "cumulusPipelineID", value: i.pipeline_data.fields.cumulusPipelineID},
		{valType: config.InfluxField, measurement: "pipeline_data", name: "gcsBucketID", value: i.pipeline_data.fields.gcsBucketID},
		{valType: config.InfluxField, measurement: "jenkins_custom_data", name: "build_result", value: i.jenkins_custom_data.fields.build_result},
		{valType: config.InfluxField, measurement: "jenkins_custom_data", name: "build_result_key", value: i.jenkins_custom_data.fields.build_result_key},
	}

	errCount := 0
	for _, metric := range measurementContent {
		err := piperenv.SetResourceParameter(path, resourceName, filepath.Join(metric.measurement, fmt.Sprintf("%vs", metric.valType), metric.name), metric.value)
		if err != nil {
			log.Entry().WithError(err).Error("Error persisting influx environment.")
			errCount++
		}
	}
	if errCount > 0 {
		log.Entry().Error("failed to persist Influx environment")
	}
}

// SapPipelineInitCommand
func SapPipelineInitCommand() *cobra.Command {
	const STEP_NAME = "sapPipelineInit"

	metadata := sapPipelineInitMetadata()
	var stepConfig sapPipelineInitOptions
	var startTime time.Time
	var commonPipelineEnvironment sapPipelineInitCommonPipelineEnvironment
	var influx sapPipelineInitInflux
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapPipelineInitCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "",
		Long:  ``,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.GithubToken)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				commonPipelineEnvironment.persist(piperOsCmd.GeneralConfig.EnvRootPath, "commonPipelineEnvironment")
				influx.persist(piperOsCmd.GeneralConfig.EnvRootPath, "influx")
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapPipelineInit(stepConfig, &stepTelemetryData, &commonPipelineEnvironment, &influx)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapPipelineInitFlags(createSapPipelineInitCmd, &stepConfig)
	return createSapPipelineInitCmd
}

func addSapPipelineInitFlags(cmd *cobra.Command, stepConfig *sapPipelineInitOptions) {
	cmd.Flags().BoolVar(&stepConfig.PipelineOptimization, "pipelineOptimization", false, "Defines if the \"Security\" and \"IPScan and PPMS\" stages run only scheduled according to the schedule defined in parameter 'nightlySchedule' in step setupPipelineEnvironment.")
	cmd.Flags().StringVar(&stepConfig.BuildURL, "buildURL", os.Getenv("PIPER_buildURL"), "")
	cmd.Flags().StringVar(&stepConfig.ProductiveBranch, "productiveBranch", os.Getenv("PIPER_productiveBranch"), "Reads the productive branch from the pipeline config yaml file.")
	cmd.Flags().BoolVar(&stepConfig.IsScheduled, "isScheduled", false, "")
	cmd.Flags().StringVar(&stepConfig.GithubAPIURL, "githubApiUrl", os.Getenv("PIPER_githubApiUrl"), "The URL to the Github API. If not the API URL will be assumed by the gitInstance.")
	cmd.Flags().StringVar(&stepConfig.PipelineID, "pipelineId", os.Getenv("PIPER_pipelineId"), "The cumulus pipelineId.")
	cmd.Flags().StringVar(&stepConfig.GithubToken, "githubToken", os.Getenv("PIPER_githubToken"), "Token of Git user for Github access.")
	cmd.Flags().BoolVar(&stepConfig.UseCommitIDForCumulus, "useCommitIdForCumulus", false, "To be set to true if cumulus storage needs to be only with commit id. If set to false, the step relies on the version parameter.")

}

// retrieve step metadata
func sapPipelineInitMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapPipelineInit",
			Aliases:     []config.Alias{{Name: "setupPipelineEnvironment", Deprecated: false}, {Name: "sapCumulusUpload", Deprecated: false}},
			Description: "",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "githubTokenCredentialsId", Description: "Jenkins 'Secret text' credentials ID containing the token used to authenticate with the Github Server.", Type: "jenkins"},
				},
				Parameters: []config.StepParameters{
					{
						Name:        "pipelineOptimization",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "GENERAL", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "buildURL",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_buildURL"),
					},
					{
						Name:        "productiveBranch",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "GENERAL"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_productiveBranch"),
					},
					{
						Name:        "isScheduled",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "githubApiUrl",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_githubApiUrl"),
					},
					{
						Name:        "pipelineId",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "gcsBucketId"}},
						Default:     os.Getenv("PIPER_pipelineId"),
					},
					{
						Name: "githubToken",
						ResourceRef: []config.ResourceReference{
							{
								Name: "githubTokenCredentialsId",
								Type: "secret",
							},

							{
								Name:    "githubTokenCredentialsVaultSecretName",
								Type:    "vaultSecret",
								Default: "github",
							},
						},
						Scope:     []string{"PARAMETERS", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{{Name: "access_token"}},
						Default:   os.Getenv("PIPER_githubToken"),
					},
					{
						Name:        "useCommitIdForCumulus",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
				},
			},
			Outputs: config.StepOutputs{
				Resources: []config.StepResources{
					{
						Name: "commonPipelineEnvironment",
						Type: "piperEnvironment",
						Parameters: []map[string]interface{}{
							{"name": "custom/isOptimizedAndScheduled", "type": "bool"},
							{"name": "custom/scheduledRun", "type": "bool"},
							{"name": "custom/cumulusPipelineID", "type": "string"},
							{"name": "custom/gcsBucketID", "type": "string"},
							{"name": "custom/isProductiveBranch", "type": "bool"},
							{"name": "custom/piperConfig", "type": "string"},
							{"name": "git/instance", "type": "string"},
							{"name": "git/repository", "type": "string"},
							{"name": "git/organization", "type": "string"},
							{"name": "git/branch", "type": "string"},
							{"name": "git/commitId", "type": "string"},
							{"name": "git/headCommitId", "type": "string"},
							{"name": "git/url", "type": "string"},
							{"name": "git/github_changes", "type": "int"},
							{"name": "git/github_additions", "type": "int"},
							{"name": "git/github_deletions", "type": "int"},
							{"name": "git/github_filesChanged", "type": "int"},
							{"name": "custom/eventData", "type": "string"},
						},
					},
					{
						Name: "influx",
						Type: "influx",
						Parameters: []map[string]interface{}{
							{"name": "step_data", "fields": []map[string]string{{"name": "build_url"}}},
							{"name": "pipeline_data", "fields": []map[string]string{{"name": "build_url"}, {"name": "github_changes"}, {"name": "github_additions"}, {"name": "github_deletions"}, {"name": "github_filesChanged"}, {"name": "cumulusPipelineID"}, {"name": "gcsBucketID"}}},
							{"name": "jenkins_custom_data", "fields": []map[string]string{{"name": "build_result"}, {"name": "build_result_key"}}},
						},
					},
				},
			},
		},
	}
	return theMetaData
}
