// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/gcs"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/piperenv"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/bmatcuk/doublestar"
	"github.com/spf13/cobra"
)

type sapReportPipelineStatusOptions struct {
	SplunkReporting         bool     `json:"splunkReporting,omitempty"`
	SplunkDsn               string   `json:"splunkDsn,omitempty"`
	SplunkToken             string   `json:"splunkToken,omitempty"`
	SplunkIndex             string   `json:"splunkIndex,omitempty"`
	TelemetryReporting      bool     `json:"telemetryReporting,omitempty"`
	SendErrorLogs           []string `json:"sendErrorLogs,omitempty" validate:"possible-values=all none build compliance config custom test service infrastructure undefined"`
	JenkinsUser             string   `json:"jenkinsUser,omitempty"`
	JenkinsToken            string   `json:"jenkinsToken,omitempty"`
	AzureToken              string   `json:"azureToken,omitempty"`
	GitHubToken             string   `json:"gitHubToken,omitempty"`
	CommitID                string   `json:"commitId,omitempty"`
	Branch                  string   `json:"branch,omitempty"`
	GitOrganization         string   `json:"gitOrganization,omitempty"`
	GitRepository           string   `json:"gitRepository,omitempty"`
	GitInstance             string   `json:"gitInstance,omitempty"`
	GitURL                  string   `json:"gitURL,omitempty"`
	ArtifactVersion         string   `json:"artifactVersion,omitempty"`
	IsOptimizedAndScheduled bool     `json:"isOptimizedAndScheduled,omitempty"`
	GcsBucketID             string   `json:"gcsBucketID,omitempty"`
	IsProductiveBranch      bool     `json:"isProductiveBranch,omitempty"`
	UseCommitIDForCumulus   bool     `json:"useCommitIdForCumulus,omitempty"`
	EventData               string   `json:"eventData,omitempty"`
}

type sapReportPipelineStatusCommonPipelineEnvironment struct {
	custom struct {
		eventData string
	}
}

func (p *sapReportPipelineStatusCommonPipelineEnvironment) persist(path, resourceName string) {
	content := []struct {
		category string
		name     string
		value    interface{}
	}{
		{category: "custom", name: "eventData", value: p.custom.eventData},
	}

	errCount := 0
	for _, param := range content {
		err := piperenv.SetResourceParameter(path, resourceName, filepath.Join(param.category, param.name), param.value)
		if err != nil {
			log.Entry().WithError(err).Error("Error persisting piper environment.")
			errCount++
		}
	}
	if errCount > 0 {
		log.Entry().Error("failed to persist Piper environment")
	}
}

type sapReportPipelineStatusReports struct {
}

func (p *sapReportPipelineStatusReports) persist(stepConfig sapReportPipelineStatusOptions, gcpJsonKeyFilePath string, gcsBucketId string, gcsFolderPath string, gcsSubFolder string) {
	if gcsBucketId == "" {
		log.Entry().Info("persisting reports to GCS is disabled, because gcsBucketId is empty")
		return
	}
	log.Entry().Info("Uploading reports to Google Cloud Storage...")
	content := []gcs.ReportOutputParam{
		{FilePattern: "**/cumulus-configuration.json", ParamRef: "", StepResultType: "root"},
		{FilePattern: "jenkins-log*.txt", ParamRef: "", StepResultType: "log"},
		{FilePattern: "**/lock-run.json", ParamRef: "", StepResultType: "root"},
		{FilePattern: "pipelineLog*.log", ParamRef: "", StepResultType: "log"},
	}

	gcsClient, err := gcs.NewClient(gcpJsonKeyFilePath, "")
	if err != nil {
		log.Entry().Errorf("creation of GCS client failed: %v", err)
		return
	}
	defer gcsClient.Close()
	structVal := reflect.ValueOf(&stepConfig).Elem()
	inputParameters := map[string]string{}
	for i := 0; i < structVal.NumField(); i++ {
		field := structVal.Type().Field(i)
		if field.Type.String() == "string" {
			paramName := strings.Split(field.Tag.Get("json"), ",")
			paramValue, _ := structVal.Field(i).Interface().(string)
			inputParameters[paramName[0]] = paramValue
		}
	}
	if err := gcs.PersistReportsToGCS(gcsClient, content, inputParameters, gcsFolderPath, gcsBucketId, gcsSubFolder, doublestar.Glob, os.Stat); err != nil {
		log.Entry().Errorf("failed to persist reports: %v", err)
	}
}

// SapReportPipelineStatusCommand Reports pipeline status and error logs
func SapReportPipelineStatusCommand() *cobra.Command {
	const STEP_NAME = "sapReportPipelineStatus"

	metadata := sapReportPipelineStatusMetadata()
	var stepConfig sapReportPipelineStatusOptions
	var startTime time.Time
	var commonPipelineEnvironment sapReportPipelineStatusCommonPipelineEnvironment
	var reports sapReportPipelineStatusReports
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapReportPipelineStatusCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "Reports pipeline status and error logs",
		Long: `This step enables the user to report the overall pipeline status and download the logfile for the pipeline run.
It also determines the Cumulus [Pipeline Execution Status](https://wiki.one.int.sap/wiki/pages/resumedraft.action?draftId=4190697507&draftShareId=c0f873e9-010b-4c9a-a6d1-f8acb51581e7&).
The status is determined by examining the pipeline logs, or querying the pipeline status through the orchestrator's API.
This requires valid orchestrator credentials to be configured for this step.`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.SplunkToken)
			log.RegisterSecret(stepConfig.JenkinsToken)
			log.RegisterSecret(stepConfig.AzureToken)
			log.RegisterSecret(stepConfig.GitHubToken)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				commonPipelineEnvironment.persist(piperOsCmd.GeneralConfig.EnvRootPath, "commonPipelineEnvironment")
				reports.persist(stepConfig, piperOsCmd.GeneralConfig.GCPJsonKeyFilePath, piperOsCmd.GeneralConfig.GCSBucketId, piperOsCmd.GeneralConfig.GCSFolderPath, piperOsCmd.GeneralConfig.GCSSubFolder)
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapReportPipelineStatus(stepConfig, &stepTelemetryData, &commonPipelineEnvironment)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapReportPipelineStatusFlags(createSapReportPipelineStatusCmd, &stepConfig)
	return createSapReportPipelineStatusCmd
}

func addSapReportPipelineStatusFlags(cmd *cobra.Command, stepConfig *sapReportPipelineStatusOptions) {
	cmd.Flags().BoolVar(&stepConfig.SplunkReporting, "splunkReporting", false, "Activates Splunk reporting.")
	cmd.Flags().StringVar(&stepConfig.SplunkDsn, "splunkDsn", os.Getenv("PIPER_splunkDsn"), "The Splunk DSN. HTTP Endpoint to HTTP-Event-Collector (HEC) from Splunk.")
	cmd.Flags().StringVar(&stepConfig.SplunkToken, "splunkToken", os.Getenv("PIPER_splunkToken"), "The Splunk token.")
	cmd.Flags().StringVar(&stepConfig.SplunkIndex, "splunkIndex", os.Getenv("PIPER_splunkIndex"), "The Splunk index.")
	cmd.Flags().BoolVar(&stepConfig.TelemetryReporting, "telemetryReporting", true, "Activates telemetry reporting for SWA.")
	cmd.Flags().StringSliceVar(&stepConfig.SendErrorLogs, "sendErrorLogs", []string{`none`}, "Send error logs? Default no error logs will be sent.")
	cmd.Flags().StringVar(&stepConfig.JenkinsUser, "jenkinsUser", os.Getenv("PIPER_jenkinsUser"), "Username for Jenkins orchestrator authentication.")
	cmd.Flags().StringVar(&stepConfig.JenkinsToken, "jenkinsToken", os.Getenv("PIPER_jenkinsToken"), "Token for Jenkins orchestrator authentication.")
	cmd.Flags().StringVar(&stepConfig.AzureToken, "azureToken", os.Getenv("PIPER_azureToken"), "Token for Azure orchestrator authentication.")
	cmd.Flags().StringVar(&stepConfig.GitHubToken, "gitHubToken", os.Getenv("PIPER_gitHubToken"), "Token for GitHub Actions orchestrator authentication.")
	cmd.Flags().StringVar(&stepConfig.CommitID, "commitId", os.Getenv("PIPER_commitId"), "CommitId of the current build.")
	cmd.Flags().StringVar(&stepConfig.Branch, "branch", os.Getenv("PIPER_branch"), "Branch of the current build.")
	cmd.Flags().StringVar(&stepConfig.GitOrganization, "gitOrganization", os.Getenv("PIPER_gitOrganization"), "Git organization of the current build.")
	cmd.Flags().StringVar(&stepConfig.GitRepository, "gitRepository", os.Getenv("PIPER_gitRepository"), "Git repository of the current build.")
	cmd.Flags().StringVar(&stepConfig.GitInstance, "gitInstance", os.Getenv("PIPER_gitInstance"), "Git instance of the current build.")
	cmd.Flags().StringVar(&stepConfig.GitURL, "gitURL", os.Getenv("PIPER_gitURL"), "Git URL of the repository.")
	cmd.Flags().StringVar(&stepConfig.ArtifactVersion, "artifactVersion", os.Getenv("PIPER_artifactVersion"), "The version assigned by artifactPrepareVersion to the uploaded log files/documents.")
	cmd.Flags().BoolVar(&stepConfig.IsOptimizedAndScheduled, "isOptimizedAndScheduled", false, "Whether the pipeline runs in optimized mode and the current execution is a scheduled one")
	cmd.Flags().StringVar(&stepConfig.GcsBucketID, "gcsBucketID", os.Getenv("PIPER_gcsBucketID"), "gcsBucketID/cumulusId of the current pipeline.")
	cmd.Flags().BoolVar(&stepConfig.IsProductiveBranch, "isProductiveBranch", false, "isProductiveBranch indicates if current pipeline is running on productive branch.")
	cmd.Flags().BoolVar(&stepConfig.UseCommitIDForCumulus, "useCommitIdForCumulus", false, "Parameter in Beta mode. To be set to true if cumulus storage needs to be only with commit id.")
	cmd.Flags().StringVar(&stepConfig.EventData, "eventData", os.Getenv("PIPER_eventData"), "Contains the \"data\" field of a CloudEvent that is used by the gcpPublishEvent step. If present, the pipeline outcome will be added to the event data.")

}

// retrieve step metadata
func sapReportPipelineStatusMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapReportPipelineStatus",
			Aliases:     []config.Alias{},
			Description: "Reports pipeline status and error logs",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "jenkinsCredentialsId", Description: "Jenkins UserID for authentication", Type: "jenkins"},
					{Name: "azureToken", Description: "Azure access token for authentication", Type: "azure"},
				},
				Parameters: []config.StepParameters{
					{
						Name:        "splunkReporting",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "splunkDsn",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{{Name: "dsn"}},
						Default:     os.Getenv("PIPER_splunkDsn"),
					},
					{
						Name:        "splunkToken",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_splunkToken"),
					},
					{
						Name:        "splunkIndex",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_splunkIndex"),
					},
					{
						Name: "telemetryReporting",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "telemetry/sapPiperPipelineStatus",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "bool",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   true,
					},
					{
						Name:        "sendErrorLogs",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     []string{`none`},
					},
					{
						Name: "jenkinsUser",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "jenkinsCredentialsId",
								Param: "username",
								Type:  "secret",
							},

							{
								Name:    "jenkinsCredentialVaultSecretName",
								Type:    "vaultSecret",
								Default: "jenkins",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{{Name: "userId"}},
						Default:   os.Getenv("PIPER_jenkinsUser"),
					},
					{
						Name: "jenkinsToken",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "jenkinsCredentialsId",
								Param: "password",
								Type:  "secret",
							},

							{
								Name:    "jenkinsCredentialVaultSecretName",
								Type:    "vaultSecret",
								Default: "jenkins",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{{Name: "token"}},
						Default:   os.Getenv("PIPER_jenkinsToken"),
					},
					{
						Name: "azureToken",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "azureToken",
								Param: "password",
								Type:  "secret",
							},

							{
								Name:    "azureCredentialVaultSecretName",
								Type:    "vaultSecret",
								Default: "azure-dev-ops",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{{Name: "token"}},
						Default:   os.Getenv("PIPER_azureToken"),
					},
					{
						Name: "gitHubToken",
						ResourceRef: []config.ResourceReference{
							{
								Name:    "githubVaultSecretName",
								Type:    "vaultSecret",
								Default: "github",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{{Name: "password"}, {Name: "access_token"}},
						Default:   os.Getenv("PIPER_gitHubToken"),
					},
					{
						Name: "commitId",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/commitId",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_commitId"),
					},
					{
						Name: "branch",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/branch",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_branch"),
					},
					{
						Name: "gitOrganization",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/organization",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitOrganization"),
					},
					{
						Name: "gitRepository",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/repository",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitRepository"),
					},
					{
						Name: "gitInstance",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/instance",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitInstance"),
					},
					{
						Name: "gitURL",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "git/url",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gitURL"),
					},
					{
						Name: "artifactVersion",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "artifactVersion",
							},
						},
						Scope:     []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_artifactVersion"),
					},
					{
						Name: "isOptimizedAndScheduled",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/isOptimizedAndScheduled",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "bool",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   false,
					},
					{
						Name: "gcsBucketID",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/gcsBucketID",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_gcsBucketID"),
					},
					{
						Name: "isProductiveBranch",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/isProductiveBranch",
							},
						},
						Scope:     []string{"PARAMETERS"},
						Type:      "bool",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   false,
					},
					{
						Name:        "useCommitIdForCumulus",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"GENERAL", "PARAMETERS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name: "eventData",
						ResourceRef: []config.ResourceReference{
							{
								Name:  "commonPipelineEnvironment",
								Param: "custom/eventData",
							},
						},
						Scope:     []string{},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_eventData"),
					},
				},
			},
			Outputs: config.StepOutputs{
				Resources: []config.StepResources{
					{
						Name: "commonPipelineEnvironment",
						Type: "piperEnvironment",
						Parameters: []map[string]interface{}{
							{"name": "custom/eventData", "type": "string"},
						},
					},
					{
						Name: "reports",
						Type: "reports",
						Parameters: []map[string]interface{}{
							{"filePattern": "**/cumulus-configuration.json", "type": "root"},
							{"filePattern": "jenkins-log*.txt", "type": "log"},
							{"filePattern": "**/lock-run.json", "type": "root"},
							{"filePattern": "pipelineLog*.log", "type": "log"},
						},
					},
				},
			},
		},
	}
	return theMetaData
}
