// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"time"

	piperOsCmd "github.com/SAP/jenkins-library/cmd"
	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/spf13/cobra"
)

type sapSUPAExecuteTestsOptions struct {
	ScriptType           string   `json:"scriptType,omitempty" validate:"possible-values=all selenium wdio qmate npm uiveri5 jmeter krypton any"`
	TestRepository       string   `json:"testRepository,omitempty"`
	TestScript           string   `json:"testScript,omitempty"`
	TestScriptFolder     string   `json:"testScriptFolder,omitempty"`
	TestRepositoryName   string   `json:"testRepositoryName,omitempty"`
	TestRepositoryBranch string   `json:"testRepositoryBranch,omitempty"`
	TestUiVeri5Params    string   `json:"testUiVeri5Params,omitempty"`
	TestWdioParams       string   `json:"testWdioParams,omitempty"`
	TestQmateParams      string   `json:"testQmateParams,omitempty"`
	TestQmateCfg         string   `json:"testQmateCfg,omitempty"`
	TestNpmParams        string   `json:"testNpmParams,omitempty"`
	TestKryptonParams    string   `json:"testKryptonParams,omitempty"`
	TestKryptonScript    string   `json:"testKryptonScript,omitempty"`
	TestKryptonRuns      string   `json:"testKryptonRuns,omitempty"`
	TestJMeterParams     string   `json:"testJMeterParams,omitempty"`
	TestJMeterScript     string   `json:"testJMeterScript,omitempty"`
	SupaConfig           string   `json:"supaConfig,omitempty"`
	CmdExe               string   `json:"cmdExe,omitempty"`
	CmdParams            string   `json:"cmdParams,omitempty"`
	ReplaceParameters    string   `json:"replaceParameters,omitempty"`
	ArchiveSUPAResult    bool     `json:"archiveSUPAResult,omitempty"`
	GithubToken          string   `json:"githubToken,omitempty"`
	SupaKeystoreKey      string   `json:"supaKeystoreKey,omitempty"`
	EnvVars              []string `json:"envVars,omitempty"`
}

// SapSUPAExecuteTestsCommand This step allows to run performance tests with SUPA
func SapSUPAExecuteTestsCommand() *cobra.Command {
	const STEP_NAME = "sapSUPAExecuteTests"

	metadata := sapSUPAExecuteTestsMetadata()
	var stepConfig sapSUPAExecuteTestsOptions
	var startTime time.Time
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createSapSUPAExecuteTestsCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "This step allows to run performance tests with SUPA",
		Long: `This step allows to run performance tests with SUPA monitoring and load tests with JMeter. Several automation frameworks for test execution are supported.

Following automation test scenarios can be executed:

- Selenium
- NPM-based scenarios (Wdio, Wdi5, general npm ..)
- JMeter
- UiVeri5

The parameter scriptType defines the automation type. The test script is provided using Github repository. The required repository URL, access token and the folder containing the test case are given as parameters.

Also multiple test runs with different automation scripts and scenarios can be started in one single Piper step.

In case of Selenium test the additionally required test class name is given in parameter testScript.
Optionally an explicit repository name (testRepositoryName) and branch name (testRepositoryBranch) can be passed. By default that name is extracted from the URL.
Further properties used for the environment variables inside the Docker container can be passed as parameter dockerEnvVars.

Additional Info regarding the execution of [Selenium test scenarios with SUPA in Docker](https://workzone.one.int.sap/site#workzone-home&/articles/eb5Ko3s5pgViDx0G7W827p).

Additional Info regarding [Performance tests in Piper](https://github.wdf.sap.corp/SAPPERF/supa-docker-perf/blob/master/doc/Setup_SUPA_Piper.md) and [SUPA Docker Container with Piper in JaaS Pipelines](https://workzone.one.int.sap/site#workzone-home&/articles/nZHsMLpGg7iWI7dBvK0zPf).

Additional Info regarding the execution of [Wdio test scenarios with SUPA in Docker](https://github.wdf.sap.corp/SAPPERF/supa-docker-perf/blob/master/doc/How_to_integrateSUPA_into_wdio.md).

Additional Info regarding the execution of [JMeter test scenarios with and without SUPA](https://workzone.one.int.sap/site#workzone-home&/articles/fUxV9HC6TJe5qYz2RcoVmO).

Additional Info regarding the execution of [UiVeri5 test scenarios with SUPA in Docker](https://github.wdf.sap.corp/SAPPERF/uiveri5-SUPA).`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(piperOsCmd.GeneralConfig.Verbose)

			piperOsCmd.GeneralConfig.GitHubAccessTokens = piperOsCmd.ResolveAccessTokens(piperOsCmd.GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = piperOsCmd.PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)
			log.RegisterSecret(stepConfig.GithubToken)
			log.RegisterSecret(stepConfig.SupaKeystoreKey)

			if len(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(piperOsCmd.GeneralConfig.HookConfig.SentryConfig.Dsn, piperOsCmd.GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: piperOsCmd.GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(piperOsCmd.GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = piperOsCmd.GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Dsn,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Token,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.Index,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						piperOsCmd.GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					err := gcp.NewGcpPubsubClient(
						vaultClient,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						piperOsCmd.GeneralConfig.CorrelationID,
						piperOsCmd.GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(piperOsCmd.GeneralConfig.HookConfig.GCPPubSubConfig.Topic, telemetryClient.GetDataBytes())
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			sapSUPAExecuteTests(stepConfig, &stepTelemetryData)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addSapSUPAExecuteTestsFlags(createSapSUPAExecuteTestsCmd, &stepConfig)
	return createSapSUPAExecuteTestsCmd
}

func addSapSUPAExecuteTestsFlags(cmd *cobra.Command, stepConfig *sapSUPAExecuteTestsOptions) {
	cmd.Flags().StringVar(&stepConfig.ScriptType, "scriptType", `all`, "Defines the script type used in the test scenario.")
	cmd.Flags().StringVar(&stepConfig.TestRepository, "testRepository", os.Getenv("PIPER_testRepository"), "URL of test repository in GitHub that should be executed.")
	cmd.Flags().StringVar(&stepConfig.TestScript, "testScript", os.Getenv("PIPER_testScript"), "Name of test scenario that should be executed (required for Selenium test scenarios).")
	cmd.Flags().StringVar(&stepConfig.TestScriptFolder, "testScriptFolder", os.Getenv("PIPER_testScriptFolder"), "Path to the folder of base directory of test scenario that should be used. For Selenium scenario equal to path of pom folder of the test (optional, default is current folder).")
	cmd.Flags().StringVar(&stepConfig.TestRepositoryName, "testRepositoryName", os.Getenv("PIPER_testRepositoryName"), "Name of test repository (optional, default is repository name given in URL).")
	cmd.Flags().StringVar(&stepConfig.TestRepositoryBranch, "testRepositoryBranch", `master`, "Name of test repository branch.")
	cmd.Flags().StringVar(&stepConfig.TestUiVeri5Params, "testUiVeri5Params", os.Getenv("PIPER_testUiVeri5Params"), "String of UiVeri5 parameter list, parameters separated by spaces. Only required for UiVeri5 test scenarios.")
	cmd.Flags().StringVar(&stepConfig.TestWdioParams, "testWdioParams", os.Getenv("PIPER_testWdioParams"), "String of WebdriverIO parameter list, parameters separated by spaces. Only required for WebdriverIO test scenarios.")
	cmd.Flags().StringVar(&stepConfig.TestQmateParams, "testQmateParams", os.Getenv("PIPER_testQmateParams"), "String of Qmate parameter list, parameters separated by spaces. Only required for Qmate test scenarios.")
	cmd.Flags().StringVar(&stepConfig.TestQmateCfg, "testQmateCfg", os.Getenv("PIPER_testQmateCfg"), "Name of Qmate configuration file. Only required for Qmate test scenarios.")
	cmd.Flags().StringVar(&stepConfig.TestNpmParams, "testNpmParams", os.Getenv("PIPER_testNpmParams"), "String of NPM parameter list, parameters separated by spaces. Only required for general NPM based test scenarios.")
	cmd.Flags().StringVar(&stepConfig.TestKryptonParams, "testKryptonParams", os.Getenv("PIPER_testKryptonParams"), "String of Krypton parameter list, parameters separated by spaces. Only required for Krypton test scenarios.")
	cmd.Flags().StringVar(&stepConfig.TestKryptonScript, "testKryptonScript", os.Getenv("PIPER_testKryptonScript"), "String contains the name of Krypton script file.")
	cmd.Flags().StringVar(&stepConfig.TestKryptonRuns, "testKryptonRuns", os.Getenv("PIPER_testKryptonRuns"), "String contains number of executed Krypton iterations.")
	cmd.Flags().StringVar(&stepConfig.TestJMeterParams, "testJMeterParams", os.Getenv("PIPER_testJMeterParams"), "String of JMeter parameter list, parameters separated by spaces. Only required for JMeter test scenarios.")
	cmd.Flags().StringVar(&stepConfig.TestJMeterScript, "testJMeterScript", os.Getenv("PIPER_testJMeterScript"), "String contains the name of JMeter script file.")
	cmd.Flags().StringVar(&stepConfig.SupaConfig, "supaConfig", os.Getenv("PIPER_supaConfig"), "String contains the name of SUPA configuration file.")
	cmd.Flags().StringVar(&stepConfig.CmdExe, "cmdExe", os.Getenv("PIPER_cmdExe"), "String of command exe, only used for testing.")
	cmd.Flags().StringVar(&stepConfig.CmdParams, "cmdParams", os.Getenv("PIPER_cmdParams"), "String of cmd parameters, separated by spaces, only used for testing.")
	cmd.Flags().StringVar(&stepConfig.ReplaceParameters, "replaceParameters", os.Getenv("PIPER_replaceParameters"), "String defines the replace parameters, replace file and replace operator.")
	cmd.Flags().BoolVar(&stepConfig.ArchiveSUPAResult, "archiveSUPAResult", false, "When true, will archive the SUPA result folder and save in project base path")
	cmd.Flags().StringVar(&stepConfig.GithubToken, "githubToken", os.Getenv("PIPER_githubToken"), "Token of Git user for Github access.")
	cmd.Flags().StringVar(&stepConfig.SupaKeystoreKey, "supaKeystoreKey", os.Getenv("PIPER_supaKeystoreKey"), "Key used to access the SUPA keystore file.")
	cmd.Flags().StringSliceVar(&stepConfig.EnvVars, "envVars", []string{}, "Additional list of properties in form of key=value. Passed to started Docker container and set as environment variables.")

	cmd.MarkFlagRequired("testRepository")
	cmd.MarkFlagRequired("githubToken")
}

// retrieve step metadata
func sapSUPAExecuteTestsMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "sapSUPAExecuteTests",
			Aliases:     []config.Alias{},
			Description: "This step allows to run performance tests with SUPA",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Secrets: []config.StepSecrets{
					{Name: "githubTokenCredentialsId", Description: "Jenkins 'Secret text' credentials ID containing the token used to authenticate with the Github Server.", Type: "jenkins"},
					{Name: "supaKeystoreKeyId", Description: "Jenkins 'Secret text' credentials ID containing the key used to access the SUPA keystore file.", Type: "jenkins"},
				},
				Parameters: []config.StepParameters{
					{
						Name:        "scriptType",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `all`,
					},
					{
						Name:        "testRepository",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testRepository"),
					},
					{
						Name:        "testScript",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testScript"),
					},
					{
						Name:        "testScriptFolder",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testScriptFolder"),
					},
					{
						Name:        "testRepositoryName",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testRepositoryName"),
					},
					{
						Name:        "testRepositoryBranch",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `master`,
					},
					{
						Name:        "testUiVeri5Params",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testUiVeri5Params"),
					},
					{
						Name:        "testWdioParams",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testWdioParams"),
					},
					{
						Name:        "testQmateParams",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testQmateParams"),
					},
					{
						Name:        "testQmateCfg",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testQmateCfg"),
					},
					{
						Name:        "testNpmParams",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testNpmParams"),
					},
					{
						Name:        "testKryptonParams",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testKryptonParams"),
					},
					{
						Name:        "testKryptonScript",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testKryptonScript"),
					},
					{
						Name:        "testKryptonRuns",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testKryptonRuns"),
					},
					{
						Name:        "testJMeterParams",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testJMeterParams"),
					},
					{
						Name:        "testJMeterScript",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_testJMeterScript"),
					},
					{
						Name:        "supaConfig",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_supaConfig"),
					},
					{
						Name:        "cmdExe",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_cmdExe"),
					},
					{
						Name:        "cmdParams",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_cmdParams"),
					},
					{
						Name:        "replaceParameters",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_replaceParameters"),
					},
					{
						Name:        "archiveSUPAResult",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name: "githubToken",
						ResourceRef: []config.ResourceReference{
							{
								Name: "githubTokenCredentialsId",
								Type: "secret",
							},

							{
								Name:    "githubTokenCredentialsVaultSecretName",
								Type:    "vaultSecret",
								Default: "github",
							},
						},
						Scope:     []string{"PARAMETERS", "STEPS"},
						Type:      "string",
						Mandatory: true,
						Aliases:   []config.Alias{{Name: "access_token"}},
						Default:   os.Getenv("PIPER_githubToken"),
					},
					{
						Name: "supaKeystoreKey",
						ResourceRef: []config.ResourceReference{
							{
								Name: "supaKeystoreKeyId",
								Type: "secret",
							},

							{
								Name:    "supaKeystoreKeyVaultSecret",
								Type:    "vaultSecret",
								Default: "supakey",
							},
						},
						Scope:     []string{"PARAMETERS", "STEPS"},
						Type:      "string",
						Mandatory: false,
						Aliases:   []config.Alias{},
						Default:   os.Getenv("PIPER_supaKeystoreKey"),
					},
					{
						Name:        "envVars",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     []string{},
					},
				},
			},
			Containers: []config.Container{
				{Image: "sapperf.int.repositories.cloud.sap/performance_scalability/supa_performance_test_all", WorkingDir: "/home/ubuntu/testautomation", Conditions: []config.Condition{{ConditionRef: "strings-equal", Params: []config.Param{{Name: "scriptType", Value: "all"}}}}},
				{Image: "sapperf.int.repositories.cloud.sap/performance_scalability/supa_performance_test", WorkingDir: "/home/ubuntu/testautomation", Conditions: []config.Condition{{ConditionRef: "strings-equal", Params: []config.Param{{Name: "scriptType", Value: "selenium"}}}}},
				{Image: "sapperf.int.repositories.cloud.sap/performance_scalability/supa_performance_test", WorkingDir: "/home/ubuntu/testautomation", Conditions: []config.Condition{{ConditionRef: "strings-equal", Params: []config.Param{{Name: "scriptType", Value: "any"}}}}},
				{Image: "sapperf.int.repositories.cloud.sap/performance_scalability/supa_performance_test", WorkingDir: "/home/ubuntu/testautomation", Conditions: []config.Condition{{ConditionRef: "strings-equal", Params: []config.Param{{Name: "scriptType", Value: "jmeter"}}}}},
				{Image: "sapperf.int.repositories.cloud.sap/performance_scalability/supa_performance_test_js", WorkingDir: "/home/ubuntu/testautomation", Conditions: []config.Condition{{ConditionRef: "strings-equal", Params: []config.Param{{Name: "scriptType", Value: "wdio"}}}}},
				{Image: "sapperf.int.repositories.cloud.sap/performance_scalability/supa_performance_test_js", WorkingDir: "/home/ubuntu/testautomation", Conditions: []config.Condition{{ConditionRef: "strings-equal", Params: []config.Param{{Name: "scriptType", Value: "npm"}}}}},
				{Image: "sapperf.int.repositories.cloud.sap/performance_scalability/supa_performance_test_js", WorkingDir: "/home/ubuntu/testautomation", Conditions: []config.Condition{{ConditionRef: "strings-equal", Params: []config.Param{{Name: "scriptType", Value: "uiveri5"}}}}},
			},
		},
	}
	return theMetaData
}
